### ISSUE TITLE
[Bug]: WS connection keeps being reset

### ISSUE THREAD

**Issue by ldorigo** [All-Hands-AI/OpenHands#2625]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

![image](https://github.com/OpenDevin/OpenDevin/assets/8631181/31a0dc9c-78ee-4eea-9b3d-aec7af09bd80)

See screenshots - stuck in a loop, ws connection keeps dropping, web app is stuck on "initializing agent"

logs:

```
0.6.2: Pulling from opendevin/opendevin
Digest: sha256:cb0a82bbc1f595fdfd146e3a0c1f1d86434200fc1db31f25013832d1dd32d427
Status: Image is up to date for ghcr.io/opendevin/opendevin:0.6.2
Starting OpenDevin...
Setting up enduser with id 1000
Docker socket group id: 965
Creating group with id 965
Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_index_client/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
There was a problem when trying to write in your cache folder (/home/enduser/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
[32mINFO[0m:     Started server process [[36m42[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:3000[0m (Press CTRL+C to quit)
[32mINFO[0m:     ('172.17.0.1', 54190) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJhOTBlZTZiMC05ZmZlLTRiMjUtYjgxNy1iZmQzYjA5OTM5ZDQifQ._U-eqYnD7YMG5KfLjwBIJ1ZXhvpK5woB93DNqnI0q2w&latest_event_id=23" [accepted]
[92m13:16:58 - opendevin:ERROR[0m: auth.py:29 - Invalid token
[32mINFO[0m:     connection open
[32mINFO[0m:     connection closed
[32mINFO[0m:     ('172.17.0.1', 54206) - "WebSocket /ws" [accepted]
[32mINFO[0m:     connection open
[92m13:17:01 - opendevin:INFO[0m: agent.py:64 - Using server runtime
[92m13:17:01 - opendevin:INFO[0m: ssh_box.py:206 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
[92m13:17:01 - opendevin:INFO[0m: ssh_box.py:248 - Detected initial session.
[92m13:17:01 - opendevin:INFO[0m: ssh_box.py:250 - Creating new Docker container
[92m13:17:01 - opendevin:WARNING[0m: ssh_box.py:700 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
[92m13:17:01 - opendevin:INFO[0m: ssh_box.py:674 - Mounting workspace directory: /home/ldorigo/Dropbox/projects/monorepo-devin
[92m13:17:01 - opendevin:INFO[0m: ssh_box.py:709 - Mounting volumes: {'/home/ldorigo/Dropbox/projects/monorepo-devin': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
[92m13:17:01 - opendevin:INFO[0m: ssh_box.py:674 - Mounting workspace directory: /home/ldorigo/Dropbox/projects/monorepo-devin
[92m13:17:01 - opendevin:INFO[0m: ssh_box.py:720 - Container started
[92m13:17:02 - opendevin:INFO[0m: ssh_box.py:736 - waiting for container to start: 1, container status: running
[92m13:17:02 - opendevin:INFO[0m: ssh_box.py:395 - Connecting to SSH session...
[92m13:17:02 - opendevin:INFO[0m: ssh_box.py:397 - You can debug the SSH connection by running: `ssh -v -p 53423 opendevin@host.docker.internal` using the password 'e72b731f-17c6-4ff4-9f79-e3cfdad0e1db'
[92m13:17:04 - opendevin:INFO[0m: ssh_box.py:401 - Connected to SSH session
[92m13:17:04 - opendevin:INFO[0m: agent.py:96 - Creating agent CodeActAgent using LLM gpt-4o
[92m13:17:04 - opendevin:INFO[0m: llm.py:120 - Initializing LLM with model: gpt-4o
[92m13:17:04 - opendevin:INFO[0m: mixin.py:32 - Initializing plugins in the sandbox
[92m13:17:04 - opendevin:INFO[0m: mixin.py:42 - Copied files from [/app/opendevin/runtime/plugins/agent_skills] to [/opendevin/plugins/agent_skills] inside sandbox.
[92m13:17:04 - opendevin:INFO[0m: mixin.py:50 - Initializing plugin [agent_skills] by executing [/opendevin/plugins/agent_skills/setup.sh] in the sandbox.
[92m13:17:18 - opendevin:INFO[0m: mixin.py:67 - Plugin agent_skills initialized successfully
[92m13:17:18 - opendevin:INFO[0m: mixin.py:42 - Copied files from [/app/opendevin/runtime/plugins/jupyter] to [/opendevin/plugins/jupyter] inside sandbox.
[92m13:17:18 - opendevin:INFO[0m: mixin.py:50 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
[92m13:17:34 - opendevin:INFO[0m: mixin.py:67 - Plugin jupyter initialized successfully
[92m13:17:34 - opendevin:INFO[0m: mixin.py:83 - Sourced ~/.bashrc successfully
[92m13:17:34 - opendevin:INFO[0m: browser_env.py:43 - Starting browser env...
[92m13:17:34 - opendevin:ERROR[0m: state.py:64 - Failed to restore state from session: sessions/2d1b7d33-6205-4fe8-89fa-3b2b87edb604/agent_state.pkl
Error restoring state sessions/2d1b7d33-6205-4fe8-89fa-3b2b87edb604/agent_state.pkl
[92m13:17:34 - opendevin:INFO[0m: agent_controller.py:183 - [Agent Controller 2d1b7d33-6205-4fe8-89fa-3b2b87edb604] Setting agent(CodeActAgent) state from AgentState.LOADING to AgentState.INIT
[92m13:17:34 - opendevin:INFO[0m: agent_controller.py:127 - [Agent Controller 2d1b7d33-6205-4fe8-89fa-3b2b87edb604] Starting step loop...
[32mINFO[0m:     ('172.17.0.1', 57932) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIyZDFiN2QzMy02MjA1LTRmZTgtODlmYS0zYjJiODdlZGI2MDQifQ.fXbHWN7XrkXym6jz85m5duvLYuDwLQPiTG4khTPtLOQ&latest_event_id=1" [accepted]
[32mINFO[0m:     connection closed
[32mINFO[0m:     connection open
[92m13:17:34 - opendevin:INFO[0m: agent_controller.py:183 - [Agent Controller 2d1b7d33-6205-4fe8-89fa-3b2b87edb604] Setting agent(CodeActAgent) state from AgentState.INIT to AgentState.STOPPED
[92m13:17:40 - opendevin:ERROR[0m: browser_env.py:117 - Browser process did not terminate, forcefully terminating...
Exception in thread Thread-1 (init_browser):
[92m13:17:40 - opendevin:INFO[0m: session.py:54 - WebSocket disconnected, sid: 2d1b7d33-6205-4fe8-89fa-3b2b87edb604
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/opendevin/runtime/browser/browser_env.py", line 45, in init_browser
[92m13:17:40 - opendevin:INFO[0m: agent_controller.py:132 - AgentController task was cancelled
    if not self.check_alive():
           ^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/browser/browser_env.py", line 104, in check_alive
    response_id, _ = self.agent_side.recv()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 248, in recv
    self._check_closed()
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 137, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
[92m13:17:40 - opendevin:INFO[0m: session.py:54 - WebSocket disconnected, sid: 2d1b7d33-6205-4fe8-89fa-3b2b87edb604
[32mINFO[0m:     connection closed
[32mINFO[0m:     ('172.17.0.1', 44034) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIyZDFiN2QzMy02MjA1LTRmZTgtODlmYS0zYjJiODdlZGI2MDQifQ.fXbHWN7XrkXym6jz85m5duvLYuDwLQPiTG4khTPtLOQ&latest_event_id=1" [accepted]
[32mINFO[0m:     connection open
[92m13:17:41 - opendevin:INFO[0m: agent.py:64 - Using server runtime
[92m13:17:41 - opendevin:INFO[0m: ssh_box.py:206 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
[92m13:17:41 - opendevin:INFO[0m: ssh_box.py:248 - Detected initial session.
[92m13:17:41 - opendevin:INFO[0m: ssh_box.py:250 - Creating new Docker container
[92m13:17:41 - opendevin:WARNING[0m: ssh_box.py:700 - Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information.
[92m13:17:41 - opendevin:INFO[0m: ssh_box.py:674 - Mounting workspace directory: /home/ldorigo/Dropbox/projects/monorepo-devin
[92m13:17:41 - opendevin:INFO[0m: ssh_box.py:709 - Mounting volumes: {'/home/ldorigo/Dropbox/projects/monorepo-devin': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
[92m13:17:41 - opendevin:INFO[0m: ssh_box.py:674 - Mounting workspace directory: /home/ldorigo/Dropbox/projects/monorepo-devin
[92m13:17:41 - opendevin:INFO[0m: ssh_box.py:720 - Container started
[92m13:17:42 - opendevin:INFO[0m: ssh_box.py:736 - waiting for container to start: 1, container status: running
[92m13:17:43 - opendevin:INFO[0m: ssh_box.py:395 - Connecting to SSH session...
[92m13:17:43 - opendevin:INFO[0m: ssh_box.py:397 - You can debug the SSH connection by running: `ssh -v -p 41733 opendevin@host.docker.internal` using the password '1a5e18a4-6e43-4e78-98c8-21a9bbd5c7b9'
[92m13:17:44 - opendevin:INFO[0m: ssh_box.py:401 - Connected to SSH session
[92m13:17:44 - opendevin:INFO[0m: agent.py:96 - Creating agent CodeActAgent using LLM gpt-4o
[92m13:17:44 - opendevin:INFO[0m: llm.py:120 - Initializing LLM with model: gpt-4o
[92m13:17:44 - opendevin:INFO[0m: mixin.py:32 - Initializing plugins in the sandbox
[92m13:17:45 - opendevin:INFO[0m: mixin.py:42 - Copied files from [/app/opendevin/runtime/plugins/agent_skills] to [/opendevin/plugins/agent_skills] inside sandbox.
[92m13:17:45 - opendevin:INFO[0m: mixin.py:50 - Initializing plugin [agent_skills] by executing [/opendevin/plugins/agent_skills/setup.sh] in the sandbox.
[92m13:17:58 - opendevin:INFO[0m: mixin.py:67 - Plugin agent_skills initialized successfully
[92m13:17:58 - opendevin:INFO[0m: mixin.py:42 - Copied files from [/app/opendevin/runtime/plugins/jupyter] to [/opendevin/plugins/jupyter] inside sandbox.
[92m13:17:58 - opendevin:INFO[0m: mixin.py:50 - Initializing plugin [jupyter] by executing [/opendevin/plugins/jupyter/setup.sh] in the sandbox.
```

### Current OpenDevin version

```bash
0.6.2
```

### Installation and Configuration

```bash
The exact docker run command from the docs. I tried with both claude-3.5 and gpt-4o with valid api keys
```

**Comment by tobitege** [comment]
Which Docker version is this happening with?

**Comment by ldorigo** [comment]
> Docker version 26.1.4, build 5650f9b102

**Comment by tobitege** [comment]
Have you tried Docker Desktop for your OS? It should be version 4.31.

**Comment by ldorigo** [comment]
Hmm, I installed docker-desktop. not sure what it changes, but now I get 

```
14:32:09 - opendevin:ERROR: ssh_box.py:257 - Failed to start Docker container, retrying...
14:32:09 - opendevin:ERROR: session.py:69 - Error creating controller: 500 Server Error for http+docker://localhost/v1.45/containers/dd9b7f2859b0f662110fdb9e8ea0ed43a56698ba42183fdb869d39a38ee7bf28/start: Internal Server Error ("Mounts denied: 
The path /tmp/cache is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/ for more info.")
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/app/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.45/containers/dd9b7f2859b0f662110fdb9e8ea0ed43a56698ba42183fdb869d39a38ee7bf28/start

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/opendevin/server/session/session.py", line 67, in _initialize_agent
    await self.agent_session.start(data)
  File "/app/opendevin/server/session/agent.py", line 46, in start
    await self._create_runtime()
  File "/app/opendevin/server/session/agent.py", line 65, in _create_runtime
    self.runtime = ServerRuntime(self.event_stream, self.sid)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/server/runtime.py", line 35, in __init__
    super().__init__(event_stream, sid, sandbox)
  File "/app/opendevin/runtime/runtime.py", line 72, in __init__
    self.sandbox = create_sandbox(sid, config.sandbox_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/runtime.py", line 46, in create_sandbox
    return DockerSSHBox(sid=sid)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/opendevin/runtime/docker/ssh_box.py", line 262, in __init__
    raise e
  File "/app/opendevin/runtime/docker/ssh_box.py", line 254, in __init__
    self.restart_docker_container()
  File "/app/opendevin/runtime/docker/ssh_box.py", line 723, in restart_docker_container
    raise ex
  File "/app/opendevin/runtime/docker/ssh_box.py", line 710, in restart_docker_container
    self.container = self.docker_client.containers.run(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/models/containers.py", line 883, in run
    container.start()
  File "/app/.venv/lib/python3.12/site-packages/docker/models/containers.py", line 420, in start
    return self.client.api.start(self.id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/container.py", line 1136, in start
    self._raise_for_status(res)
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.45/containers/dd9b7f2859b0f662110fdb9e8ea0ed43a56698ba42183fdb869d39a38ee7bf28/start: Internal Server Error ("Mounts denied: 
The path /tmp/cache is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/ for more info.")
```

**Comment by PierrunoYT** [comment]
The error message indicates that Docker is unable to start the container because the path `/tmp/cache` is not shared from the host and is not known to Docker. This is a common issue when Docker is not configured to share certain directories with containers.

Here are the steps to resolve this issue:

1. **Configure Docker to Share the Path**:
   - Open Docker Desktop.
   - Go to `Preferences` (or `Settings` on Windows).
   - Navigate to `Resources` -> `File Sharing`.
   - Add `/tmp/cache` to the list of shared paths.
   - Apply and restart Docker.

2. **Verify Docker Configuration**:
   Ensure that Docker is running and properly configured to share the necessary paths. You can verify this by running:
   ```bash
   docker info
   ```
   and checking the `File Descriptors` section to see if the paths are correctly shared.

3. **Check Docker Version**:
   Make sure you are using a compatible version of Docker. Sometimes, upgrading Docker to the latest version can resolve such issues.

4. **Update Docker Configuration in Code**:
   If the path `/tmp/cache` is hardcoded in your code, consider making it configurable. This can be done by updating the configuration files or environment variables used in your Docker setup.

5. **Refer to Docker Documentation**:
   For more details on configuring shared paths, refer to the Docker documentation: [Docker File Sharing](https://docs.docker.com/desktop/mac/#file-sharing).

6. **Check the Troubleshooting Guide**:
   The repository includes a troubleshooting guide that might have additional information on resolving Docker-related issues. You can find it in `/docs/modules/usage/troubleshooting/troubleshooting.md`.

By following these steps, you should be able to resolve the issue with Docker not being able to start the container due to the unshared path. If the problem persists, consider checking the Docker logs for more detailed error messages and further debugging.

**Comment by ldorigo** [comment]
Note that there's still a line "There was a problem when trying to write in your cache folder (/home/enduser/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory. ", not sure if it's normal.

**Comment by ldorigo** [comment]
Update: this only happens on firefox. It works on chrome.

**Comment by RaunakChhatwal** [comment]
Please don't close this.

**Comment by neubig** [comment]
@RaunakChhatwal : are you encountering something similar? Any information you could provide would be helpful!

**Comment by tobitege** [comment]
@neubig I think in your log it looks like that packages got installed during one session.
In that case, the server runtime tries to restart the Jupyter kernel and sends it a SHUTDOWN.
I don't have enough time to look more closely into this, if this is also the reason for the full re-start of the session itself. 🤔

**Comment by neubig** [comment]
Thanks @tobitege , that's a good point. Maybe it's just not rebooting gracefully enough?

**Comment by neubig** [comment]
We have another issue #2765 that's also about websocket, so maybe we can consolidate the discussion there.
