### ISSUE TITLE
[Bug]: When installing on WSL, I get a "No files in workspace" message at the top of the screen 

### ISSUE THREAD

**Issue by yf007** [All-Hands-AI/OpenHands#2861]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [x] I have checked the existing issues.

### Describe the bug

When installing on WSL, I get a "No files in workspace" message at the top of the screen 
![image](https://github.com/OpenDevin/OpenDevin/assets/18291801/06a75253-4965-4717-92ef-31947b704f41)

### Current OpenDevin version

```bash
Last
```

### Installation and Configuration

```bash
through the guide from here
https://github.com/OpenDevin/OpenDevin/blob/main/Development.md
```

### Logs, Errors, Screenshots, and Additional Context

CodeActAgent LEVEL 0 STEP 0

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/main.py", line 2309, in completion
    response = bedrock_converse_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/llms/bedrock_httpx.py", line 1855, in completion
    sigv4.add_auth(request)
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yf007/OpenDevin/opendevin/controller/agent_controller.py", line 134, in _start_step_loop
    await self._step()
  File "/home/yf007/OpenDevin/opendevin/controller/agent_controller.py", line 334, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/OpenDevin/agenthub/codeact_agent/codeact_agent.py", line 194, in step
    response = self.llm.completion(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/OpenDevin/opendevin/llm/llm.py", line 215, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 1001, in wrapper
    raise e
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 881, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/main.py", line 2674, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 7665, in exception_type
    raise e
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 6430, in exception_type
    response=original_exception.response,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoCredentialsError' object has no attribute 'response'
02:40:42 - opendevin:ERROR: agent_controller.py:140 - Error while running the agent: 'NoCredentialsError' object has no attribute 'response'
02:40:42 - opendevin:ERROR: agent_controller.py:141 - Traceback (most recent call last):
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/main.py", line 2309, in completion
    response = bedrock_converse_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/llms/bedrock_httpx.py", line 1855, in completion
    sigv4.add_auth(request)
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yf007/OpenDevin/opendevin/controller/agent_controller.py", line 134, in _start_step_loop
    await self._step()
  File "/home/yf007/OpenDevin/opendevin/controller/agent_controller.py", line 334, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/OpenDevin/agenthub/codeact_agent/codeact_agent.py", line 194, in step
    response = self.llm.completion(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/OpenDevin/opendevin/llm/llm.py", line 215, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 1001, in wrapper
    raise e
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 881, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/main.py", line 2674, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 7665, in exception_type
    raise e
  File "/home/yf007/.cache/pypoetry/virtualenvs/opendevin-8vL8ErdM-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 6430, in exception_type
    response=original_exception.response,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoCredentialsError' object has no attribute 'response'

02:40:42 - OBSERVATION
ErrorObservation(content='There was an unexpected error while running the agent', observation='error')
INFO:     127.0.0.1:51358 - "GET /api/list-files?path=%2F HTTP/1.1" 200 OK
Exception in thread Thread-1 (init_browser):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yf007/OpenDevin/opendevin/runtime/browser/browser_env.py", line 72, in init_browser
    raise BrowserInitException('Failed to start browser environment.')
opendevin.core.exceptions.BrowserInitException: Failed to start browser environment.

**Comment by enyst** [comment]
That is a very weird log... According to the screenshot you didn't yet send any message to the agent? Also, can you please tell, did you set your LLM model and your credentials in the UI Settings before this?

It might be worth trying to do this:
`git reset --hard e6ebb4307e9a39a20b180100bc338b5b45646655`
`make build`
`make run`

And please tell if it makes a difference.

**Comment by ENS16** [comment]
Hello, I am getting the same error, how can I solve this?

**Comment by ENS16** [comment]
Hello, I am getting the same error, how can I solve this?

**Comment by mamoodi** [comment]
Is it clear that the "No files in workspace" is related to the error?
If I have an empty workspace, I also get a "No files in workspace" in the UI after each prompt which is a little annoying. However, I am able to interact with OpenDevin. And the UI popup goes away if I just put any file in the workspace or ask OpenDevin to create a file in the workspace.

In your case are you able to prompt OpenDevin?

**Comment by SmartManoj** [comment]
@yf007 Are you using AWS bedrock? If so, could you check [this](https://docs.litellm.ai/docs/providers/bedrock#usage)?

**Comment by SmartManoj** [comment]
This issue contains two problems.

1. "No files in workspace" popup
2. AttributeError: 'NoCredentialsError' object has no attribute 'response'

---

> I also get a "No files in workspace" in the UI after each prompt

The file explorer refreshes if the agent state changes. And if no file is there, the toast will occur every time.

Do you have any proposed solution?

**Comment by mamoodi** [comment]
No. I usually just tell it to create a "hello.rb" file so the toast doesn't pop up after each prompt.

**Comment by mamoodi** [comment]
@ENS16 and @yf007 are you all still getting this error on the latest main?
I'm getting a little bit of a different behavior than what I used to get (my OpenDevin still worked though).

Make sure you set your workspace_base to an absolute path.
