### ISSUE TITLE
[Bug]: pip install (through Jupyter?) not consistently working

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#3203]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I asked OpenDevin to write a script that uses matplotlib. OpenDevin installed matplotlib (twice) through jupyter, but even after installing the matplotlib library was not recognized. Then it installed through bash and things seemed to have worked. The log is below.

```log
08:49:22 - opendevin:INFO: agent_controller.py:347 - CodeActAgent LEVEL 0 LOCAL STEP 2 GLOBAL STEP 2
08:49:23 - opendevin:INFO: llm.py:181 - Cost: 0.03 USD | Accumulated Cost: 0.07 USD
08:49:23 - opendevin:INFO: agent_controller.py:426 - **CmdRunAction (source=EventSource.AGENT)**
THOUGHT: Let's run the script to count the `.doc` and `.docx` files and generate the plot.
COMMAND:
python3 count_documents.py
08:49:23 - opendevin:INFO: agent_controller.py:200 - **CmdOutputObservation (source=EventSource.AGENT, exit code=1)**
Traceback (most recent call last):
  File "/workspace/count_documents.py", line 3, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
08:49:23 - opendevin:INFO: agent_controller.py:347 - CodeActAgent LEVEL 0 LOCAL STEP 3 GLOBAL STEP 3
08:49:24 - opendevin:INFO: llm.py:181 - Cost: 0.03 USD | Accumulated Cost: 0.10 USD
08:49:24 - opendevin:INFO: agent_controller.py:426 - **IPythonRunCellAction**
THOUGHT: It seems that `matplotlib` is not installed. Let's install it first.
CODE:
%pip install matplotlib
08:49:30 - opendevin:INFO: agent_controller.py:200 - **IPythonRunCellObservation**
[Package installed successfully]
[Kernel restarted successfully to load the package]
08:49:30 - opendevin:INFO: agent_controller.py:347 - CodeActAgent LEVEL 0 LOCAL STEP 4 GLOBAL STEP 4
08:49:31 - opendevin:INFO: llm.py:181 - Cost: 0.03 USD | Accumulated Cost: 0.12 USD
08:49:31 - opendevin:INFO: agent_controller.py:426 - **CmdRunAction (source=EventSource.AGENT)**
THOUGHT: Now that `matplotlib` is installed, let's run the script again to count the `.doc` and `.docx` files and generate the plot.
COMMAND:
python3 count_documents.py
08:49:32 - opendevin:INFO: agent_controller.py:200 - **CmdOutputObservation (source=EventSource.AGENT, exit code=1)**
Traceback (most recent call last):
  File "/workspace/count_documents.py", line 3, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
08:49:32 - opendevin:INFO: agent_controller.py:347 - CodeActAgent LEVEL 0 LOCAL STEP 5 GLOBAL STEP 5
08:49:33 - opendevin:INFO: llm.py:181 - Cost: 0.03 USD | Accumulated Cost: 0.15 USD
08:49:33 - opendevin:INFO: agent_controller.py:426 - **IPythonRunCellAction**
THOUGHT: It seems that the installation of `matplotlib` did not persist. Let's try installing it again and then running the script.
CODE:
%pip install matplotlib
08:49:34 - opendevin:INFO: agent_controller.py:200 - **IPythonRunCellObservation**
[Package already installed]
08:49:34 - opendevin:INFO: agent_controller.py:347 - CodeActAgent LEVEL 0 LOCAL STEP 6 GLOBAL STEP 6
08:49:35 - opendevin:INFO: llm.py:181 - Cost: 0.03 USD | Accumulated Cost: 0.18 USD
08:49:35 - opendevin:INFO: agent_controller.py:426 - **CmdRunAction (source=EventSource.AGENT)**
THOUGHT: It seems that the package is already installed, but the script is still not recognizing it. Let's try running the script again to see if it works this time.
COMMAND:
python3 count_documents.py
08:49:35 - opendevin:INFO: agent_controller.py:200 - **CmdOutputObservation (source=EventSource.AGENT, exit code=1)**
Traceback (most recent call last):
  File "/workspace/count_documents.py", line 3, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
08:49:35 - opendevin:INFO: agent_controller.py:347 - CodeActAgent LEVEL 0 LOCAL STEP 7 GLOBAL STEP 7
08:49:38 - opendevin:INFO: llm.py:181 - Cost: 0.03 USD | Accumulated Cost: 0.20 USD
08:49:38 - opendevin:INFO: agent_controller.py:426 - **CmdRunAction (source=EventSource.AGENT)**
THOUGHT: It seems there might be an issue with the environment not recognizing the installed package. Let's try installing `matplotlib` using a different method and then running the script again.

I'll use the `--user` flag to ensure it's installed in the user directory.
COMMAND:
pip install --user matplotlib
08:49:42 - opendevin:INFO: agent_controller.py:200 - **CmdOutputObservation (source=EventSource.AGENT, exit code=0)**
[Package installed successfully]
08:49:42 - opendevin:INFO: agent_controller.py:347 - CodeActAgent LEVEL 0 LOCAL STEP 8 GLOBAL STEP 8
08:49:44 - opendevin:INFO: llm.py:181 - Cost: 0.03 USD | Accumulated Cost: 0.23 USD
08:49:44 - opendevin:INFO: agent_controller.py:426 - **CmdRunAction (source=EventSource.AGENT)**
THOUGHT: Now that `matplotlib` is installed in the user directory, let's try running the script again to count the `.doc` and `.docx` files and generate the plot.
COMMAND:
python3 count_documents.py
08:49:45 - opendevin:INFO: agent_controller.py:200 - **CmdOutputObservation (source=EventSource.AGENT, exit code=0)**

08:49:45 - opendevin:INFO: agent_controller.py:347 - CodeActAgent LEVEL 0 LOCAL STEP 9 GLOBAL STEP 9
08:49:47 - opendevin:INFO: llm.py:181 - Cost: 0.03 USD | Accumulated Cost: 0.26 USD
08:49:47 - opendevin:INFO: agent_controller.py:426 - **CmdRunAction (source=EventSource.AGENT)**
THOUGHT: The script executed successfully without any errors. Let's check if the plot image `documents_by_year.png` was created.
COMMAND:
ls -l documents_by_year.png
```

### Current OpenDevin version

```bash
commit 21ea9953b3026223f65a04cf5699d6ad0915bfa7
```

### Installation and Configuration

```bash
make build; make run
```

### Operating System

- Operating system: Mac OS Sonoma
- Sandbox: default

**Comment by mamoodi** [comment]
This looks similar to this issue: #3098

**Comment by neubig** [comment]
I haven't encountered this recently so it may be fixed.
