### ISSUE TITLE
[Bug]: PermissionError with Podman on Ubuntu 22.04 (docker container not running after `make start-backend`)

### ISSUE THREAD

**Issue by Domiii** [All-Hands-AI/OpenHands#3246]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

* I first encountered some sort of `PermissionError(13, 'Permission denied')` error (don't have the full log anymore).
* Then I ran `chmod 777 /run/podman/podman.sock`
* Then I followed [these instructions](https://github.com/containers/podman/issues/13468#issuecomment-1062764637): `export DOCKER_HOST="unix:/run/podman/podman.sock"`
* Then I restarted and retried navigating to http://localhost:3000.
* Observation: `docker ps` does not list any container.
* Observation: This is the error I get (with `DEBUG` enabled):
  ```sh
  $ make start-backend

  Starting backend...
  INFO:     Will watch for changes in these directories: ['/home/domi/OpenDevin']
  INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
  WARNING:  --reload-include and --reload-exclude have no effect unless watchfiles is installed.
  INFO:     Started reloader process [38953] using StatReload
  00:36:22 - opendevin:INFO: config.py:495 - Attempt to load default LLM config from config toml
  INFO:     Started server process [38957]
  INFO:     Waiting for application startup.
  INFO:     Application startup complete.
  INFO:     127.0.0.1:57674 - "GET / HTTP/1.1" 304 Not Modified
  INFO:     127.0.0.1:57674 - "GET /api/options/models HTTP/1.1" 200 OK
  INFO:     127.0.0.1:57674 - "GET /api/options/agents HTTP/1.1" 200 OK
  INFO:     ('127.0.0.1', 35040) - "WebSocket /ws" [accepted]
  INFO:     connection open
  00:36:49 - opendevin:INFO: agent.py:79 - Using runtime: server
  00:36:49 - opendevin:INFO: ssh_box.py:135 - SSHBox is running as opendevin user with USER_ID=1000 in the sandbox
  DDBG self.unix_socket=/run/podman/podman.sock, self.base_url=http+docker://localhost/version
  00:36:49 - opendevin:ERROR: ssh_box.py:142 - Error creating controller. Please check Docker is running and visit `https://docs.all-hands.dev/modules/usage/troubleshooting` for more debugging information.
  00:36:49 - opendevin:ERROR: session.py:116 - Error creating controller: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
  Traceback (most recent call last):
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
      response = self._make_request(
                ^^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
      conn.request(
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/urllib3/connection.py", line 398, in request
      self.endheaders()
    File "/usr/lib/python3.11/http/client.py", line 1298, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/usr/lib/python3.11/http/client.py", line 1058, in _send_output
      self.send(msg)
    File "/usr/lib/python3.11/http/client.py", line 996, in send
      self.connect()
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/docker/transport/unixconn.py", line 27, in connect
      sock.connect(self.unix_socket)
  PermissionError: [Errno 13] Permission denied

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
      resp = conn.urlopen(
            ^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
      retries = retries.increment(
                ^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/urllib3/util/retry.py", line 474, in increment
      raise reraise(type(error), error, _stacktrace)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/urllib3/util/util.py", line 38, in reraise
      raise value.with_traceback(tb)
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
      response = self._make_request(
                ^^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
      conn.request(
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/urllib3/connection.py", line 398, in request
      self.endheaders()
    File "/usr/lib/python3.11/http/client.py", line 1298, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/usr/lib/python3.11/http/client.py", line 1058, in _send_output
      self.send(msg)
    File "/usr/lib/python3.11/http/client.py", line 996, in send
      self.connect()
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/docker/transport/unixconn.py", line 27, in connect
      sock.connect(self.unix_socket)
  urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
      return self.version(api_version=False)["ApiVersion"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/docker/api/daemon.py", line 181, in version
      return self._result(self._get(url), json=True)
                          ^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/docker/utils/decorators.py", line 44, in inner
      return f(self, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/docker/api/client.py", line 246, in _get
      return self.get(url, **self._set_request_timeout(kwargs))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
      return self.request("GET", url, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
      resp = self.send(prep, **send_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
      r = adapter.send(request, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/requests/adapters.py", line 682, in send
      raise ConnectionError(err, request=request)
  requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/home/domi/OpenDevin/opendevin/server/session/session.py", line 106, in _initialize_agent
      await self.agent_session.start(
    File "/home/domi/OpenDevin/opendevin/server/session/agent.py", line 54, in start
      await self._create_runtime(runtime_name, config, agent)
    File "/home/domi/OpenDevin/opendevin/server/session/agent.py", line 81, in _create_runtime
      self.runtime = runtime_cls(
                    ^^^^^^^^^^^^
    File "/home/domi/OpenDevin/opendevin/runtime/server/runtime.py", line 49, in __init__
      self.sandbox = self.create_sandbox(sid, config.sandbox.box_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/domi/OpenDevin/opendevin/runtime/server/runtime.py", line 63, in create_sandbox
      return DockerSSHBox(
            ^^^^^^^^^^^^^
    File "/home/domi/OpenDevin/opendevin/runtime/docker/ssh_box.py", line 146, in __init__
      raise ex
    File "/home/domi/OpenDevin/opendevin/runtime/docker/ssh_box.py", line 140, in __init__
      self.docker_client = docker.from_env()
                          ^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/docker/client.py", line 94, in from_env
      return cls(
            ^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/docker/client.py", line 45, in __init__
      self.api = APIClient(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/docker/api/client.py", line 207, in __init__
      self._version = self._retrieve_server_version()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/domi/.cache/pypoetry/virtualenvs/opendevin-BHW4dODp-py3.11/lib/python3.11/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
      raise DockerException(
  docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
  ```

## Q:
* How do I fix this?
* How do I make sure that the docker server is up and running?

### Current OpenDevin version

```bash
* `pyproject.toml` says `0.8.3`
```

### Installation and Configuration

```bash
I followed the steps in `Development.md`:

* I made sure I have the correct version of dependencies installed globally.
* I installed podman for docker (because that was recommended to me for docker installations in the past).
* `make build`
* `make setup-config`
* `make start-backend`
```

### Operating System

Ubuntu 22.04

### Reproduction Steps

`make start-backend`

**Comment by aglassoforange** [comment]
Hi, I encountered the same issue on my MacBook. I resolved it by updating Docker to the latest version (4.33.0).
