### ISSUE TITLE
[DevOps]: Integration test regeneration and `tests/runtime/test_*.py` stall

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#3568]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I'm trying to regenerate integration tests for [this PR](https://github.com/All-Hands-AI/OpenHands/pull/3548) and in my environment when I run the regeneration script:

```bash
git fetch origin fix-pypi-package
git checkout fix-pypi-package
TEST_RUNTIME=eventstream ./tests/integration/regenerate.sh
```

Alternatively, even on main I see that the following command fails.

```bash
poetry run pytest tests/runtime/test_*.py
```

 it stalls and then eventually times out.

### Current OpenHands version

```bash
b72599379d6ce3e6abdb5cd28c6b091cfe8b36b2

(the final commit on the above PR)
```

### Installation and Configuration

```bash
make build
```

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

Full log

```
$ TEST_RUNTIME=eventstream ./tests/integration/regenerate.sh
Current working directory: /Users/gneubig/work/OpenHands
SCRIPT_DIR: /Users/gneubig/work/OpenHands/tests/integration
PROJECT_ROOT: /Users/gneubig/work/OpenHands
WORKSPACE_BASE: /Users/gneubig/work/OpenHands/_test_workspace
WORKSPACE_MOUNT_PATH: /Users/gneubig/work/OpenHands/_test_workspace
TEST_RUNTIME: eventstream




========STEP 1: Running test_edits for DelegatorAgent========




/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"

  warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
============================= test session starts ==============================
platform darwin -- Python 3.11.9, pytest-8.3.2, pluggy-1.5.0 -- /Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/bin/python
cachedir: .pytest_cache
rootdir: /Users/gneubig/work/OpenHands
configfile: pytest.ini
plugins: asyncio-0.24.0, cov-5.0.0, Faker-27.4.0, anyio-4.4.0, forked-1.6.0
asyncio: mode=Mode.STRICT, default_loop_scope=None
collecting ... 
Paths used:
workspace_base: /Users/gneubig/work/OpenHands/_test_workspace
workspace_mount_path: /Users/gneubig/work/OpenHands/_test_workspace
workspace_mount_path_in_sandbox: /workspace
CONFIG: AppConfig(llms={'llm': LLMConfig(model='claude-3-5-sonnet-20240620', api_key='******', base_url=None, api_version=None, embedding_model='local', embedding_base_url=None, embedding_deployment_name=None, aws_access_key_id=None, aws_secret_access_key=None, aws_region_name=None, num_retries=10, retry_multiplier=2, retry_min_wait=3, retry_max_wait=300, timeout=None, max_message_chars=10000, temperature=0, top_p=0.5, custom_llm_provider=None, max_input_tokens=None, max_output_tokens=None, input_cost_per_token=None, output_cost_per_token=None, ollama_base_url=None, drop_params=None)}, agents={'agent': AgentConfig(memory_enabled=False, memory_max_threads=2, llm_config=None)}, default_agent='DelegatorAgent', sandbox=SandboxConfig(api_hostname='localhost', container_image='nikolaik/python-nodejs:python3.11-nodejs22', user_id=501, timeout=120, enable_auto_lint=False, use_host_network=True, initialize_plugins=True, runtime_extra_deps=None, runtime_startup_env_vars={}, browsergym_eval_env=None), security=SecurityConfig(confirmation_mode=False, security_analyzer=None), runtime='eventstream', file_store='memory', file_store_path='/tmp/file_store', workspace_base='/Users/gneubig/work/OpenHands/_test_workspace', workspace_mount_path='/Users/gneubig/work/OpenHands/_test_workspace', workspace_mount_path_in_sandbox='/workspace', workspace_mount_rewrite=None, cache_dir='/tmp/cache', run_as_openhands=True, max_iterations=15, max_budget_per_task=15, e2b_api_key=None, disable_color=False, jwt_secret='******', debug=False, enable_cli_session=False, file_uploads_max_file_size_mb=0, file_uploads_restrict_file_types=False, file_uploads_allowed_extensions=['.*']
collected 1 item

tests/integration/test_agent.py::test_edits 22:39:49 - openhands:INFO: main.py:75 - Initializing runtime: <class 'openhands.runtime.client.runtime.EventStreamRuntime'>
22:39:49 - openhands:INFO: runtime_build.py:41 - Using project root: /Users/gneubig/work/OpenHands
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - poetry-core
* Getting build dependencies for sdist...
* Building sdist...
Successfully built openhands_ai-0.9.0.tar.gz
22:39:52 - openhands:INFO: runtime_build.py:59 - Source distribution created at /Users/gneubig/work/OpenHands/dist/openhands_ai-0.9.0.tar.gz
22:39:52 - openhands:INFO: runtime_build.py:80 - Source distribution moved to /var/folders/12/vk4h8csj4ts7rql173zqn0sm0000gn/T/tmp7h1i2iot/project.tar.gz
22:39:52 - openhands:INFO: runtime_build.py:90 - Unpacked source code directory: /var/folders/12/vk4h8csj4ts7rql173zqn0sm0000gn/T/tmp7h1i2iot/code
22:39:52 - openhands:INFO: runtime_build.py:161 - Input base image: nikolaik/python-nodejs:python3.11-nodejs22
Skip init: False
Extra deps: None
Hash for docker build directory [/var/folders/12/vk4h8csj4ts7rql173zqn0sm0000gn/T/tmp7h1i2iot] (contents: ['Dockerfile', 'code']): 163ba92f78d4107a4e3fa9b7ce6b2e4b

22:39:52 - openhands:INFO: runtime_build.py:247 - Image [ghcr.io/all-hands-ai/runtime:163ba92f78d4107a4e3fa9b7ce6b2e4b] already exists so we will reuse it.
22:39:52 - openhands:INFO: runtime.py:183 - Starting container with image: ghcr.io/all-hands-ai/runtime:163ba92f78d4107a4e3fa9b7ce6b2e4b and name: openhands-sandbox-1622d1b4-8b0a-4f71-b9b2-32ed7c89d8ba_47f6bb569a34e4ed_d8f59e45-3116-4191-8ed0-59d983db1219
22:39:52 - openhands:WARNING: runtime.py:196 - Using host network mode. If you are using MacOS, please make sure you have the latest version of Docker Desktop and enabled host network feature: https://docs.docker.com/network/drivers/host/#docker-desktop
22:39:52 - openhands:INFO: runtime.py:204 - Mount dir: /workspace
22:39:52 - openhands:INFO: runtime.py:238 - Container started. Server url: http://localhost:63193
22:39:52 - openhands:INFO: runtime.py:157 - Container initialized with plugins: []
22:39:52 - openhands:INFO: runtime.py:160 - Container initialized with env vars: None
22:39:52 - openhands:INFO: main.py:151 - Agent Controller Initialized: Running agent DelegatorAgent, model claude-3-5-sonnet-20240620, with task: "Fix typos in bad.txt. Do not ask me for confirmation at any point."
22:39:52 - openhands:INFO: agent_controller.py:150 - [Agent Controller default] Starting step loop...
22:39:52 - USER_ACTION
**MessageAction** (source=EventSource.USER)
CONTENT: Fix typos in bad.txt. Do not ask me for confirmation at any point.


==============
DelegatorAgent LEVEL 0 LOCAL STEP 0 GLOBAL STEP 0

22:39:53 - ACTION
AgentDelegateAction(agent='StudyRepoForTaskAgent', inputs={'task': 'Fix typos in bad.txt. Do not ask me for confirmation at any point.'}, thought='', action='delegate')
22:39:53 - openhands:INFO: agent_controller.py:330 - [Agent Controller default]: start delegate, creating agent StudyRepoForTaskAgent using LLM LLM(model=claude-3-5-sonnet-20240620)


==============
StudyRepoForTaskAgent LEVEL 1 LOCAL STEP 0 GLOBAL STEP 1

22:39:53 - openhands:INFO: llm.py:431 - Cost: 1.00 USD | Accumulated Cost: 1.00 USD
22:39:53 - ACTION
**CmdRunAction (source=EventSource.AGENT)**
COMMAND:
ls
22:39:53 - openhands:INFO: runtime.py:325 - Awaiting session
22:40:03 - openhands:INFO: runtime.py:265 - 
------------------------------Container logs:------------------------------
    |Starting action execution API on port 63193
    |02:39:56 - openhands:INFO: client.py:689 - Starting action execution API on port 63193
    |INFO:     Started server process [15]
    |INFO:     Waiting for application startup.
    |02:39:57 - openhands:INFO: browser_env.py:58 - Starting browser env...
    |02:40:00 - openhands:INFO: browser_env.py:101 - Browser env started.
    |02:40:00 - openhands:INFO: client.py:197 - Initializing by running 3 bash commands...
    |02:40:00 - openhands:INFO: client.py:208 - Bash init commands completed
    |02:40:00 - openhands:INFO: client.py:482 - Runtime client initialized.
    |INFO:     Application startup complete.
    |INFO:     Uvicorn running on http://0.0.0.0:63193 (Press CTRL+C to quit)
------------------------------------------------------------------------------------------
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-22' coro=<Runtime.on_event() done, defined at /Users/gneubig/work/OpenHands/openhands/runtime/runtime.py:129> exception=RetryError(<Future at 0x139cfa9d0 state=finished raised ClientConnectorError>)>
Traceback (most recent call last):
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1073, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/aiohappyeyeballs/impl.py", line 122, in start_connection
    raise OSError(first_errno, msg)
ConnectionRefusedError: [Errno 61] Multiple exceptions: [Errno 61] Connect call failed ('::1', 64777, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 64777)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gneubig/work/OpenHands/openhands/runtime/client/runtime.py", line 276, in _wait_until_alive
    async with session.get(f'{self.api_url}/alive') as response:
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/aiohttp/client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1088, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:64777 ssl:default [Multiple exceptions: [Errno 61] Connect call failed ('::1', 64777, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 64777)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gneubig/work/OpenHands/openhands/runtime/runtime.py", line 135, in on_event
    observation = await self.run_action(event)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gneubig/work/OpenHands/openhands/runtime/client/runtime.py", line 327, in run_action
    await self._wait_until_alive()
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gneubig/Library/Caches/pypoetry/virtualenvs/openhands-ai-mHbwbJq6-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x139cfa9d0 state=finished raised ClientConnectorError>]
```

**Comment by tobitege** [comment]
Maybe IPv6 is an issue as the error mentions `::1`

**Comment by Kaushikdkrikhanu** [comment]
If this is set to False it works: https://github.com/All-Hands-AI/OpenHands/blob/653bc4ef6d8ed9dd864caf11697651c58fb5d299/tests/integration/test_agent.py#L32
