### ISSUE TITLE
[Bug]: Ctrl+C no longer stops the app (sometimes?)

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#3876]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When running with `make run`, with UI, Ctrl+C in the terminal used to stop the app. It may have been needed twice, but no more, and it worked to stop fairly quickly. Now it looks like it broke:

This log is after Ctrl+C. Every time the console added text, I did Ctrl+C over and over again. It still added stuff.

<details>
<summary> Click to expand log</summary>

```
20:11:09 - openhands:DEBUG: stream.py:134 - Adding CmdOutputObservation id=57 from AGENT
20:11:09 - openhands:INFO: session.py:139 - Server event
INFO:     Shutting down
20:11:09 - openhands:INFO: agent_controller.py:215
OBSERVATION
**CmdOutputObservation (source=EventSource.AGENT, exit code=0)**
[2] 377

[Python Interpreter: /openhands/poetry/openhands-ai-5O4_aCHf-py3.11/bin/python]
openhands@57acf8a48a2e:/workspace $ 
20:11:09 - openhands:INFO: session.py:139 - Server event


==============
CodeActAgent LEVEL 0 LOCAL STEP 13 GLOBAL STEP 23

20:11:09 - openhands:DEBUG: logger.py:238 - Logging to /Users/enyst/repos/odie/logs/llm/24-09-15_20-04/prompt_022.log

openhands-py3.12(base) ➜  odie git:(enyst/groq) ✗ 20:11:23 - openhands:DEBUG: logger.py:238 - Logging to /Users/enyst/repos/odie/logs/llm/24-09-15_20-04/response_022.log
20:11:23 - openhands:INFO: llm.py:515 - Input tokens: 6511
Output tokens: 78

20:11:23 - openhands:DEBUG: stream.py:134 - Adding CmdRunAction id=58 from AGENT
20:11:23 - openhands:INFO: agent_controller.py:489
ACTION
**CmdRunAction (source=EventSource.AGENT)**
THOUGHT: Let me check the server log:
COMMAND:
cat server.log
20:11:23 - openhands:DEBUG: stream.py:134 - Adding MessageAction id=59 from USER
20:11:23 - openhands:INFO: runtime.py:414 - Awaiting session
20:11:23 - openhands:DEBUG: runtime.py:296 - Getting container logs...
20:11:23 - openhands:INFO: runtime.py:307 - 
-----------------------------------Container logs:-----------------------------------
    |INFO:     192.168.65.1:36096 - "GET /alive HTTP/1.1" 200 OK
--------------------------------------------------------------------------------
20:11:23 - openhands:DEBUG: runtime.py:296 - Getting container logs...
20:11:23 - openhands:INFO: runtime.py:307 - 
-----------------------------------Container logs:-----------------------------------
    |INFO:     192.168.65.1:39314 - "GET /alive HTTP/1.1" 200 OK
    |18:11:23 - openhands:DEBUG: client.py:357 - Running action:
    |**CmdRunAction (source=EventSource.AGENT)**
    |THOUGHT: Let me check the server log:
    |COMMAND:
    |cat server.log
    |18:11:23 - openhands:DEBUG: bash.py:39 - BASH PARSING command: cat server.log
    |18:11:23 - openhands:DEBUG: bash.py:46 - BASH PARSING remaining:
    |18:11:23 - openhands:DEBUG: client.py:305 - Executing command: cat server.log
    |18:11:23 - openhands:DEBUG: client.py:331 - Requesting exit code...
    |18:11:23 - openhands:DEBUG: client.py:359 - Action output:
    |**CmdOutputObservation (source=None, exit code=0)**
    | * Serving Flask app 'app'
    | * Debug mode: off
    |Address already in use
    |Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
    |[2]+  Exit 1                  python3 app.py > server.log 2>&1
    |
    |[Python Interpreter: /openhands/poetry/openhands-ai-5O4_aCHf-py3.11/bin/python]
    |openhands@57acf8a48a2e:/workspace $
    |INFO:     192.168.65.1:39314 - "POST /execute_action HTTP/1.1" 200 OK
--------------------------------------------------------------------------------
20:11:23 - openhands:DEBUG: stream.py:134 - Adding CmdOutputObservation id=60 from AGENT
20:11:23 - openhands:INFO: session.py:139 - Server event
INFO:     Waiting for background tasks to complete. (CTRL+C to force quit)
20:11:23 - openhands:INFO: agent_controller.py:179
USER_ACTION
**MessageAction** (source=EventSource.USER)
CONTENT: stop
20:11:23 - openhands:DEBUG: stream.py:134 - Adding NullObservation id=61 from USER
INFO:     connection closed
20:11:23 - openhands:INFO: agent_controller.py:215
OBSERVATION
**CmdOutputObservation (source=EventSource.AGENT, exit code=0)**
 * Serving Flask app 'app'
 * Debug mode: off
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2]+  Exit 1                  python3 app.py > server.log 2>&1

[Python Interpreter: /openhands/poetry/openhands-ai-5O4_aCHf-py3.11/bin/python]
openhands@57acf8a48a2e:/workspace $ 
20:11:23 - openhands:INFO: session.py:139 - Server event


==============
CodeActAgent LEVEL 0 LOCAL STEP 14 GLOBAL STEP 24

20:11:23 - openhands:DEBUG: logger.py:238 - Logging to /Users/enyst/repos/odie/logs/llm/24-09-15_20-04/prompt_023.log

openhands-py3.12(base) ➜  odie git:(enyst/groq) ✗ 20:11:36 - openhands:DEBUG: logger.py:238 - Logging to /Users/enyst/repos/odie/logs/llm/24-09-15_20-04/response_023.log
20:11:36 - openhands:INFO: llm.py:515 - Input tokens: 6669
Output tokens: 141

20:11:36 - openhands:DEBUG: stream.py:134 - Adding CmdRunAction id=62 from AGENT
20:11:36 - openhands:INFO: agent_controller.py:489
ACTION
**CmdRunAction (source=EventSource.AGENT)**
THOUGHT: It seems that port 5000 is already in use by another program. Let me stop the server and start it again with a different port:
COMMAND:
kill 377
20:11:36 - openhands:DEBUG: state.py:103 - Saving state to session 6afecf2e-4cc9-430e-bddf-72b3601905a9:AgentState.RUNNING
20:11:36 - openhands:DEBUG: agent_controller.py:238 - [Agent Controller 6afecf2e-4cc9-430e-bddf-72b3601905a9] Setting agent(CodeActAgent) state from AgentState.RUNNING to AgentState.STOPPED
20:11:36 - openhands:DEBUG: stream.py:134 - Adding AgentStateChangedObservation id=63 from AGENT

openhands-py3.12(base) ➜  odie git:(enyst/groq) ✗ 20:11:41 - openhands:INFO: session.py:65 - WebSocket disconnected, sid: 6afecf2e-4cc9-430e-bddf-72b3601905a9
20:11:41 - openhands:INFO: runtime.py:414 - Awaiting session
20:11:41 - openhands:DEBUG: runtime.py:296 - Getting container logs...
20:11:41 - openhands:INFO: runtime.py:307 - 
-----------------------------------Container logs:-----------------------------------
    |INFO:     192.168.65.1:39314 - "GET /alive HTTP/1.1" 200 OK
--------------------------------------------------------------------------------

openhands-py3.12(base) ➜  odie git:(enyst/groq) ✗ 20:11:43 - openhands:DEBUG: runtime.py:296 - Getting container logs...

openhands-py3.12(base) ➜  odie git:(enyst/groq) ✗ 20:11:47 - openhands:DEBUG: runtime.py:296 - Getting container logs...

openhands-py3.12(base) ➜  odie git:(enyst/groq) ✗ 
openhands-py3.12(base) ➜  odie git:(enyst/groq) ✗ 20:11:55 - openhands:DEBUG: runtime.py:296 - Getting container logs...

openhands-py3.12(base) ➜  odie git:(enyst/groq) ✗ 20:12:11 - openhands:DEBUG: runtime.py:296 - Getting container logs...

openhands-py3.12(base) ➜  odie git:(enyst/groq) ✗ 20:12:31 - openhands:DEBUG: runtime.py:296 - Getting container logs...
20:12:51 - openhands:DEBUG: runtime.py:296 - Getting container logs...

openhands-py3.12(base) ➜  odie git:(enyst/groq) ✗ 20:13:11 - openhands:DEBUG: runtime.py:296 - Getting container logs...
20:13:31 - openhands:DEBUG: runtime.py:296 - Getting container logs...
```

</details>

Notes:
- it made 2 more complete steps (agent steps, trips to the LLM), that I tried to interrupt
- then it kept trying to get container logs. After _every_ line above "Getting container logs" I did Ctrl+C over and over. 😅 

Finally, I left it alone to do whatever it likes, and it eventually finished:

<details>
<summary> Click to expand log</summary>

```
openhands-py3.12(base) ➜  odie git:(enyst/groq) ✗ 20:13:51 - openhands:DEBUG: runtime.py:296 - Getting container logs...
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-278' coro=<Runtime.on_event() done, defined at /Users/enyst/repos/odie/openhands/runtime/runtime.py:109> exception=ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=38765): Max retries exceeded with url: /alive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16e08c650>: Failed to establish a new connection: [Errno 61] Connection refused'))"))>
Traceback (most recent call last):
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 398, in request
    self.endheaders()
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 236, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x16e08c650>: Failed to establish a new connection: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=38765): Max retries exceeded with url: /alive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16e08c650>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/enyst/repos/odie/openhands/runtime/runtime.py", line 115, in on_event
    observation = self.run_action(event)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/openhands/runtime/client/runtime.py", line 415, in run_action
    self._wait_until_alive()
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/openhands/runtime/client/runtime.py", line 336, in _wait_until_alive
    response = self.session.get(f'{self.api_url}/alive')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=38765): Max retries exceeded with url: /alive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16e08c650>: Failed to establish a new connection: [Errno 61] Connection refused'))
20:13:51 - openhands:INFO: session.py:139 - Server event
20:13:51 - openhands:INFO: session.py:139 - Server event
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [38570]
```

</details>

### Current OpenHands version

```bash
Current main - commit https://github.com/All-Hands-AI/OpenHands/commit/ecf4aed28b0cf7c18d4d8ff554883ba182fc6bdd
```

### Installation and Configuration

```bash
make build
make run

Custom model: openai/llama3-8b-8192
Base URL: https://api.groq.com/openai/v1

I use python 3.12, though this likely doesn't matter.
```

### Model and Agent

Llama3-8b-8192
CodeActAgent

### Operating System

Mac OS

### Reproduction Steps

1. `make build`
2. `make run`
3. Tell the agent "42", and it started to run the example in the prompt
4. Ctrl+C while the agent is running.

It didn't always happen, but maybe 2 out of 3, from what I see, something is eating keyboard interrupts.

If that doesn't work to replicate the issue, try resetting task from the UI button, and give it a very different task, then interrupt after it starts, that also resulted in some behavior where it kept forever trying to get container logs, ignoring repeated attempts to stop it.

**Comment by enyst** [comment]
It might be related to this: https://github.com/All-Hands-AI/OpenHands/pull/3870 due to the suspicious behavior when it insists on getting container logs repeatedly. Still, it doesn't seem to explain all the strange behavior? Like: I think at least twice, it did connect to the LLM after Ctrl+C, we should stop the main loop at Ctrl+C.

**Comment by tobitege** [comment]
What I don't understand is that my PR's workflows were all successful and on merge started to fail and other PR's now suddenly also fail in integration tests, where they were successful just earlier. 🤔 

But as to the issue: the added call for _wait_for_alive basically adds another tenacity retry loop to it, which I guess catches the sigint, thus eating the CTRL+C

**Comment by enyst** [comment]
That sounds right, can't we just exclude this from that retry?
