### ISSUE TITLE
[Bug]: While running remote runtime evaluation, I encountered a '413 Client Error: Request Entity Too Large for URL' error.

### ISSUE THREAD

**Issue by aglassoforange** [All-Hands-AI/OpenHands#4042]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I used this command to run remote Eval:

`ALLHANDS_API_KEY="YOUR-API-KEY" RUNTIME=remote EVAL_DOCKER_IMAGE_PREFIX="us-docker.pkg.dev/evaluation-428620/swe-bench-images" evaluation/swe_bench/scripts/eval_infer_remote.sh evaluation/outputs/swe_bench_lite/CodeActAgent/Llama-3.1-70B-Instruct-Turbo_maxiter_30_N_v1.9-no-hint/output.jsonl 16 "princeton-nlp/SWE-bench_Lite" "test"`

During this process there are multiple instances failed to be evaluated. Below is the instances that encountered this issue.
[sphinx-doc__sphinx-11445, sphinx-doc__sphinx-8474, sphinx-doc__sphinx-7686, sphinx-doc__sphinx-7686]
```

[92m20:37:32 - openhands:INFO[0m: shared.py:378 - Starting evaluation for instance sphinx-doc__sphinx-11445.
Hint: run "tail -f /Users/y/Documents/project/OpenHands/evaluation/evaluation_outputs/outputs/swe-bench-lite/CodeActAgent/o1-mini_maxiter_30_N_v1.9-no-hint/output.logs/instance_sphinx-doc__sphinx-11445.log" to see live logs in a separate shell
----------
Error in instance [pytest-dev__pytest-5692]: Copy operation failed: 413 Client Error: Request Entity Too Large for url: https://6fc2518e-3ac5-4bfc-acdc-72ef90de1a87.runtime.all-hands.dev/upload_file?destination=%2Ftmp&recursive=false. Stacktrace:
Traceback (most recent call last):
  File "/Users/y/Documents/project/OpenHands/openhands/runtime/remote/runtime.py", line 326, in copy_to
    response = send_request(
               ^^^^^^^^^^^^^
  File "/Users/y/Documents/project/OpenHands/openhands/runtime/utils/request.py", line 62, in send_request
    return _send_request_with_retry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y/Library/Caches/pypoetry/virtualenvs/openhands-ai-AWLCSgR9-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/y/Library/Caches/pypoetry/virtualenvs/openhands-ai-AWLCSgR9-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y/Library/Caches/pypoetry/virtualenvs/openhands-ai-AWLCSgR9-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/y/Library/Caches/pypoetry/virtualenvs/openhands-ai-AWLCSgR9-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/y/opt/anaconda3/envs/py3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/y/opt/anaconda3/envs/py3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/y/Library/Caches/pypoetry/virtualenvs/openhands-ai-AWLCSgR9-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/y/Documents/project/OpenHands/openhands/runtime/utils/request.py", line 59, in _send_request_with_retry
    response.raise_for_status()
  File "/Users/y/Library/Caches/pypoetry/virtualenvs/openhands-ai-AWLCSgR9-py3.11/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Request Entity Too Large for url: https://6fc2518e-3ac5-4bfc-acdc-72ef90de1a87.runtime.all-hands.dev/upload_file?destination=%2Ftmp&recursive=false

```

### Current OpenHands version

```bash
0.9.4 (updated 4 days ago)
```

### Installation and Configuration

```bash
3757  RUNTIME=remote EVAL_DOCKER_IMAGE_PREFIX="us-docker.pkg.dev/evaluation-428620/swe-bench-images" evaluation/swe_bench/scripts/eval_infer_remote.sh evaluation/evaluation_outputs/outputs/swe-bench-lite/CodeActAgent/o1-mini_maxiter_30_N_v1.9-no-hint/output.jsonl 16 "princeton-nlp/SWE-bench_Lite" "test" >eval_log.log 2>&1\n
```

### Model and Agent

o1-mini
Code Act Agent

### Operating System

MacOs

**Comment by tobitege** [comment]
I'm getting this error on `main` currently with fresh docker image when trying to submit a (small even) image.
