### ISSUE TITLE
[Bug]: `ERROR:asyncio:Task exception was never retrieved`

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#4071]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

CC: @mamoodi @tofarr 
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-2' coro=<SessionManager._cleanup_sessions() done, defined at /Users/stephanpsaras/Desktop/aha/OpenHands/openhands/server/session/manager.py:52> exception=AttributeError("'coroutine' object has no attribute 'cancel'")>
Traceback (most recent call last):
  File "/Users/.../OpenHands/openhands/server/session/manager.py", line 67, in _cleanup_sessions
    await to_del_session.close()
  File "/Users/.../OpenHands/openhands/server/session/session.py", line 53, in close
    await self.agent_session.close()
  File "/Users/.../OpenHands/openhands/server/session/agent_session.py", line 120, in close
    await self.controller.close()
  File "/Users/.../OpenHands/openhands/controller/agent_controller.py", line 123, in close
    self.agent_task.cancel()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'cancel'
```

I think it throws after being idle for a while, maybe when it tries to remove an inactive session? It doesn’t seem to be a deadly error though

### Current OpenHands version

```bash
0.9.4
```

### Installation and Configuration

```bash
make run
```

### Reproduction Steps

1. Start session
2. Idle until error

**Comment by tobitege** [comment]
Fixed by #4075
