### ISSUE TITLE
[Bug]: 503 errors in evals with the RemoteRuntime

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#4353]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Lately I don't seem able to run more than one or a few swe-bench instances on the remote runtime, in part due to the LLM proxy errors, and also this. I'll limit this report to the runtime. FWIW sometimes I'm trying to run a small subset of 10-30 instances, most of the time I keep trying to run a subset of 93.

I guess we know how this error looks like from the client side 😅, I'm attaching a log below though.

`Error in instance [astropy__astropy-6938]: 503 Server Error: Service Unavailable for url: https://1edcb116-09f8-4527-9bf1-aacceae5f0a6-40dbdee44b9ae0dc.eval-runtime.all-hands.dev/alive.`

More importantly, I have some hope that maybe I'm doing something wrong, maybe using something outdated, can you please check these:

> ALLHANDS_API_KEY="ah-stuff" RUNTIME=remote SANDBOX_REMOTE_RUNTIME_API_URL="https://runtime.eval.all-hands.dev" EVAL_DOCKER_IMAGE_PREFIX="us-central1-docker.pkg.dev/evaluation-092424/swe-bench-images" \
./evaluation/swe_bench/scripts/run_infer.sh llm.deepseek-8k HEAD CodeActAgent 93 50 16 "princeton-nlp/SWE-bench_Lite" test

The branch doesn't appear to matter. Current `main`, CoAct PR, other branches, almost-main, etc, run into the same errors. Are they not supposed to work? (but at least CoAct PR and `main` did work ~3 weeks ago).

Should I use a different eval docker prefix? Did we add/change some vars that influence this?

What confuses me the most is that **one instance** goes through, maybe a few more (if the stars align right 🤣), they do execute actions, and maybe one instance will even see a successful finish, and then it all fails. Sometimes (rarely) I remembered to clean up the runtimes, but it did not seem to make a difference.

Note: It was worse with the LLM proxy (with its 502 errors plus 503 from the runtime, almost no instance could go through), without the proxy it seems to execute now more than a few, but it's still riddled by these errors.

Note: sometimes it's a 404:
`Instance django__django-12470 - 2024-10-12 23:15:58,965 - ERROR - 404 Client Error: Not Found for url: https://f7d89ad2-5813-4b95-9650-c4232fb417dd-0768779e5e3d3179.eval-runtime.all-hands.dev/alive`
And sometimes (more rarely I think) it's a Timeout.

### OpenHands Installation

Development workflow

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

<details>

----------[The above error occurred. Retrying... (attempt 4 of 5)]----------

Instance django__django-11848 - 2024-10-12 22:54:55,286 - ERROR - ----------
Error in instance [django__django-11848]: 503 Server Error: Service Unavailable for url: https://59279533-dea9-4023-8e22-1072419f5a31-2f7de1ac766fc27b.eval-runtime.all-hands.dev/alive. Stacktrace:
Traceback (most recent call last):
  File "/Users/enyst/repos/OpenHands/evaluation/utils/shared.py", line 281, in _process_instance_wrapper
    result = process_instance_func(instance, metadata, use_mp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/evaluation/swe_bench/run_infer.py", line 368, in process_instance
    runtime = create_runtime(config)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/core/main.py", line 74, in create_runtime
    runtime: Runtime = runtime_cls(
                       ^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 86, in __init__
    self._start_or_attach_to_runtime(plugins)
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 119, in _start_or_attach_to_runtime
    self._wait_until_alive()
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 265, in _wait_until_alive
    response = send_request_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/utils/request.py", line 66, in send_request_with_retry
    return _send_request_with_retry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/utils/request.py", line 63, in _send_request_with_retry
    response.raise_for_status()
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://59279533-dea9-4023-8e22-1072419f5a31-2f7de1ac766fc27b.eval-runtime.all-hands.dev/alive

----------[The above error occurred. Retrying... (attempt 4 of 5)]----------

----------
Error in instance [django__django-11848]: 503 Server Error: Service Unavailable for url: https://59279533-dea9-4023-8e22-1072419f5a31-2f7de1ac766fc27b.eval-runtime.all-hands.dev/alive. Stacktrace:
Traceback (most recent call last):
  File "/Users/enyst/repos/OpenHands/evaluation/utils/shared.py", line 281, in _process_instance_wrapper
    result = process_instance_func(instance, metadata, use_mp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/evaluation/swe_bench/run_infer.py", line 368, in process_instance
    runtime = create_runtime(config)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/core/main.py", line 74, in create_runtime
    runtime: Runtime = runtime_cls(
                       ^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 86, in __init__
    self._start_or_attach_to_runtime(plugins)
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 119, in _start_or_attach_to_runtime
    self._wait_until_alive()
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 265, in _wait_until_alive
    response = send_request_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/utils/request.py", line 66, in send_request_with_retry
    return _send_request_with_retry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/utils/request.py", line 63, in _send_request_with_retry
    response.raise_for_status()
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://59279533-dea9-4023-8e22-1072419f5a31-2f7de1ac766fc27b.eval-runtime.all-hands.dev/alive

----------[The above error occurred. Retrying... (attempt 4 of 5)]----------

Instance django__django-11620 - 2024-10-12 22:54:55,331 - ERROR - ----------
Error in instance [django__django-11620]: 503 Server Error: Service Unavailable for url: https://5c676ff0-b126-4a59-a621-a6bf3d6d7708-fe4f593a17cc6a23.eval-runtime.all-hands.dev/alive. Stacktrace:
Traceback (most recent call last):
  File "/Users/enyst/repos/OpenHands/evaluation/utils/shared.py", line 281, in _process_instance_wrapper
    result = process_instance_func(instance, metadata, use_mp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/evaluation/swe_bench/run_infer.py", line 368, in process_instance
    runtime = create_runtime(config)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/core/main.py", line 74, in create_runtime
    runtime: Runtime = runtime_cls(
                       ^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 86, in __init__
    self._start_or_attach_to_runtime(plugins)
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 119, in _start_or_attach_to_runtime
    self._wait_until_alive()
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 265, in _wait_until_alive
    response = send_request_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/utils/request.py", line 66, in send_request_with_retry
    return _send_request_with_retry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/utils/request.py", line 63, in _send_request_with_retry
    response.raise_for_status()
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://5c676ff0-b126-4a59-a621-a6bf3d6d7708-fe4f593a17cc6a23.eval-runtime.all-hands.dev/alive

----------[The above error occurred. Retrying... (attempt 4 of 5)]----------

----------
Error in instance [django__django-11620]: 503 Server Error: Service Unavailable for url: https://5c676ff0-b126-4a59-a621-a6bf3d6d7708-fe4f593a17cc6a23.eval-runtime.all-hands.dev/alive. Stacktrace:
Traceback (most recent call last):
  File "/Users/enyst/repos/OpenHands/evaluation/utils/shared.py", line 281, in _process_instance_wrapper
    result = process_instance_func(instance, metadata, use_mp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/evaluation/swe_bench/run_infer.py", line 368, in process_instance
    runtime = create_runtime(config)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/core/main.py", line 74, in create_runtime
    runtime: Runtime = runtime_cls(
                       ^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 86, in __init__
    self._start_or_attach_to_runtime(plugins)
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 119, in _start_or_attach_to_runtime
    self._wait_until_alive()
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/remote/runtime.py", line 265, in _wait_until_alive
    response = send_request_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/utils/request.py", line 66, in send_request_with_retry
    return _send_request_with_retry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/OpenHands/openhands/runtime/utils/request.py", line 63, in _send_request_with_retry
    response.raise_for_status()
  File "/Users/enyst/repos/OpenHands/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://5c676ff0-b126-4a59-a621-a6bf3d6d7708-fe4f593a17cc6a23.eval-runtime.all-hands.dev/alive
</details>

**Comment by mamoodi** [comment]
Do you still run into this issue? I think something was fixed regarding the image names but don't know if it's related to this issue.

The 404 issues are known and there isn't a good solution for it right now :(

**Comment by enyst** [comment]
Thanks for the reminder! I didn't run into (visible) errors last week, on a relatively significant bunch of tasks.

I think there have indeed been things solved with it. Let's close this, and we'll see what else comes up.
