### ISSUE TITLE
[Bug]: Connection Timeout Error with Docker Internal Host

### ISSUE THREAD

**Issue by kittenvr** [All-Hands-AI/OpenHands#4586]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I am experiencing a ConnectTimeout error when trying to connect to host.docker.internal on port 34848. The application retries multiple times but ultimately fails.

Steps to Reproduce:
1. Start the application.
2. Attempt to connect to `host.docker.internal`.
3. Observe the connection attempts and timeout error.

Expected Behavior:
The application should successfully connect to `host.docker.internal` without timing out.

Actual Behavior:
The application fails to connect and raises a `ConnectTimeout` error.

### OpenHands Installation

Docker command in README

### OpenHands Version

main

### Operating System

Linux

### Logs, Errors, Screenshots, and Additional Context

024-10-25 14:28:23,835 - ERROR - Runtime initialization failed: HTTPConnectionPool(host='host.docker.internal', port=34848): Max retries exceeded with url: /alive (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ec378ae6a50>, 'Connection to host.docker.internal timed out. (connect timeout=310)'))
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 208, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7ec378ae6a50>, 'Connection to host.docker.internal timed out. (connect timeout=310)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=34848): Max retries exceeded with url: /alive (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ec378ae6a50>, 'Connection to host.docker.internal timed out. (connect timeout=310)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/openhands/server/session/agent_session.py", line 188, in _create_runtime
    await self.runtime.connect()
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 217, in connect
    self._wait_until_alive()
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 382, in _wait_until_alive
    response = send_request_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/utils/request.py", line 96, in send_request_with_retry
    return _send_request_with_retry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/utils/request.py", line 92, in _send_request_with_retry
    response = session.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='host.docker.internal', port=34848): Max retries exceeded with url: /alive (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ec378ae6a50>, 'Connection to host.docker.internal timed out. (connect timeout=310)'))
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='host.docker.internal', port=34848): Max retries exceeded with url: /alive (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ec378ae6a50>, 'Connection to host.docker.internal timed out. (connect timeout=310)'))"))>
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 208, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7ec378ae6a50>, 'Connection to host.docker.internal timed out. (connect timeout=310)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=34848): Max retries exceeded with url: /alive (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ec378ae6a50>, 'Connection to host.docker.internal timed out. (connect timeout=310)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 88, in _start_thread
    asyncio.run(self._start(*args), debug=True)
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 106, in _start
    await self._create_runtime(
  File "/app/openhands/server/session/agent_session.py", line 188, in _create_runtime
    await self.runtime.connect()
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 217, in connect
    self._wait_until_alive()
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 382, in _wait_until_alive
    response = send_request_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/utils/request.py", line 96, in send_request_with_retry
    return _send_request_with_retry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/utils/request.py", line 92, in _send_request_with_retry
    response = session.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='host.docker.internal', port=34848): Max retries exceeded with url: /alive (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7ec378ae6a50>, 'Connection to host.docker.internal timed out. (connect timeout=310)'))

**Comment by tofarr** [comment]
host.docker.internal is a docker desktop feature - are you perchance using docker engine?

**Comment by tofarr** [comment]
If so, I think we'll need to update our troubleshooting steps.

**Comment by kittenvr** [comment]
I'm just using the dicker command

**Comment by tofarr** [comment]
There is a nice comment on this thread: https://forums.docker.com/t/difference-between-docker-desktop-and-docker-engine/124612 : 
"Basically Docker Desktop is a virtual machine + Graphical user interface with some extra features like the new extensions and running a single-node Kubernetes “cluster” easily."

One of these "extra features" is the secret sauce that makes requests from inside a container route requests to "docker.host.internal" to the correct port / container on localhost. (Otherwise these mappings would need to be established manually.)

I see 2 alternatives open to you.

## 1. Download and install docker desktop

There are some steps for installing on linux here: https://docs.docker.com/desktop/install/linux/

## 2. Run the server outside docker.

The server will still create sandboxed runtimes using docker engine, but unlike the docker command, the main server will run outside a container - This is what we do when developing, so you'll need to manage poetry, npm and a bunch of other dependencies. Details are here: https://github.com/All-Hands-AI/OpenHands/blob/main/Development.md

**Comment by kittenvr** [comment]
> There is a nice comment on this thread: https://forums.docker.com/t/difference-between-docker-desktop-and-docker-engine/124612 : "Basically Docker Desktop is a virtual machine + Graphical user interface with some extra features like the new extensions and running a single-node Kubernetes “cluster” easily."
> 
> One of these "extra features" is the secret sauce that makes requests from inside a container route requests to "docker.host.internal" to the correct port / container on localhost. (Otherwise these mappings would need to be established manually.)
> 
> I see 2 alternatives open to you.
> ## 1. Download and install docker desktop
> 
> There are some steps for installing on linux here: https://docs.docker.com/desktop/install/linux/
> ## 2. Run the server outside docker.
> 
> The server will still create sandboxed runtimes using docker engine, but unlike the docker command, the main server will run outside a container - This is what we do when developing, so you'll need to manage poetry, npm and a bunch of other dependencies. Details are here: https://github.com/All-Hands-AI/OpenHands/blob/main/Development.md

is using the aur version of docker desktop also good?

**Comment by jakehemmerle** [comment]
The reason `openhands-app` can't find the runtime container is because it is trying to contact the runtime via the binded port on `host.docker.internal` instead of the ip address of the newly created container.

I confirmed this in docker engine by running`docker exec -it openhands-app /bin/bash` and trying `curl host.docker.internal:31931`, which doesn't resolve anything. When I `curl 172.17.0.3:31931`, which is the ip of the newly created runtime, it *does* return a JSON object after the runtime container is up and running. I suspect that the Developer Environment, even when using docker engine, will work fine, because 31931 gets binded to the host properly and I can always access it via localhost.

I think the fix will be this simple and I'd like to solve this. Would one of the devs be willing to sponsor me by giving me a quick rundown of the codebase? Do you have a discord or something? I will check dev docs later today

**Comment by skylarmb** [comment]
Are you including `--add-host host.docker.internal:host-gateway` in your docker command? Without that I dont think `host.docker.internal` resolves to anything. [The docker command in the docs](https://docs.all-hands.dev/modules/usage/installation#start-the-app) includes this and I was able to set it up to point to my local ollama just fine just using this command. I just had to configure the `Base URL` in the UI settings to be `http://host.docker.internal:11434` and then it worked.

**Comment by avi12** [comment]
I'm also experiencing this issue
Docker command via PowerShell:
```powershell
docker run -it --rm --pull=always `
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:main-nikolaik `
    -e LOG_ALL_EVENTS=true `
    -v /var/run/docker.sock:/var/run/docker.sock `
    -p 3000:3000 `
    --add-host host.docker.internal:host-gateway `
    --name openhands-app `
    docker.all-hands.dev/all-hands-ai/openhands:0.15
```
Conversation history: https://www.all-hands.dev/share?share_id=86be867b0d24b24c5522cf7331419d17b80929b909cefaacdcca4cd3b70b383c
LLM: https://huggingface.co/matteogeniaccio/phi-4 via https://lmstudio.ai

**Comment by TonyGiorgio** [comment]
There's a lot of quality of life things here that don't allow for running openhands properly. I've tried everything above and it still doesn't work.

1. Not installing docker desktop on a server, it shouldn't be needed. 
2. Can't change the host that it tries to query, should be an environment variable at the very least. 
3. Can't change the port it runs off of.
4. Not running this as a server outside of docker.

**Comment by jmtatsch** [comment]
Same issue here.
Not sure what is expected to be running on that port like 38749 of the host operating system.

**Comment by slgotting** [comment]
Not sure how anyone has gotten this to work by default, given the fact that docker apparently doesnt expose containers via the bridge ip, which is what host.docker.internal points to.

My fix worked (at least for now):

1. I cloned the repo ( git clone git@github.com:All-Hands-AI/OpenHands.git )
2. add this line to the ./docker-compose.yml file (under the openhands service):

         `network_mode: host`

3. Then from that directory run `docker-compose up`

This took me a long time to figure out so if it works for you please thumbs up

**Comment by jlundan** [comment]
Not sure if this is related, but at least I could get this working by pointing host.docker.internal to 127.0.0.1. Since you mentioned that you are using just the docker command, I am assuming you are on Linux. When you use host networking, you basically expose your PC networking to the container. So contacting localhost on your container, would contact the network interface on your host machine (your PC). Since the openhands docker container seems to try to use  'host.docker.internal' for communications with the client, that I think should point to your localhost, where your runtime container runs. Since --add-host allows only ip addresses, I think you should have

```
docker run -it --rm --pull=always \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.27-nikolaik \
    -e LOG_ALL_EVENTS=true \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v ~/.openhands-state:/.openhands-state \
    -p 3000:3000 \
    --add-host host.docker.internal:127.0.0.1 \
    --network=host \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.27
```

A big disclaimer: I am just starting working with OpenHands, and have absolutely no idea of the security implications of this. Maybe someone from the development team could comment this, but this way I got it working at least on my Ubuntu 24.04 machine without using Docker Desktop.

**Comment by itaosan** [comment]
@jlundan 
I am using Ubuntu and had a similar problem, but I ran it with the command you gave me and it works.
Thank you very much. Thank you!
