### ISSUE TITLE
[Bug]: Command ... `docker buildx build` ... returned non-zero exit status 125

### ISSUE THREAD

**Issue by Domiii** [All-Hands-AI/OpenHands#4607]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

* Update to latest (https://github.com/replayio-public/OpenHands/commit/30eeaa641c5e38cc820ae27421d81a148f7af337)
* `poetry install`
* `DEBUG=1 make run > tmp.log 2>&1`
* Open the frontend and enter any query (e.g. `"test"`).
* ERROR: Command ... `docker buildx build` ... returned non-zero exit status 125

NOTE: I also removed all existing images. `docker images` does not list any `all-hands` images.

### OpenHands Installation

Happens to me using any workflow:
* `make run` causes this
* but it also happens when starting backend independently: `make start-backend`

### OpenHands Version

30eeaa641c5e38cc820ae27421d81a148f7af337

### Operating System

Linux

### Logs, Errors, Screenshots, and Additional Context

Log:

```
[33mRunning the app...(B[m
[33mStarting backend server...(B[m
[33mWaiting for the backend to start...(B[m
DEBUG:openhands:DEBUG mode enabled.
[92m19:36:54 - openhands:DEBUG[0m: logger.py:239 - Logging initialized
[92m19:36:54 - openhands:DEBUG[0m: logger.py:251 - Logging to file in: /home/path/to/OpenHands/logs
[92m19:36:56 - openhands:DEBUG[0m: utils.py:136 - Attempt to load default LLM config from config toml
[92m19:36:56 - openhands:DEBUG[0m: listen.py:156 - File upload config: max_size=0MB, restrict_types=False, allowed_extensions=['.*']
INFO:     Started server process [1386272]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
[32mBackend started successfully.(B[m
[33mStarting frontend...(B[m

> openhands-frontend@0.11.0 dev
> npm run make-i18n && VITE_MOCK_API=false remix vite:dev --port 3001 --host 127.0.0.1


> openhands-frontend@0.11.0 make-i18n
> node scripts/make-i18n-translations.cjs

  ➜  Local:   http://127.0.0.1:3001/
  ➜  press h + enter to show help


Source path: /home/path/to/OpenHands/frontend/src/index.css
Setting up new context...


Source path: /home/path/to/OpenHands/frontend/src/tailwind.css
Setting up new context...
Finding changed files: 7.919ms
JIT TOTAL: 464.171ms


(node:1386496) Warning: Label 'JIT TOTAL' already exists for console.time()
(Use `node --trace-warnings ...` to show where the warning was created)
Reading changed files: 227.044ms
Sorting candidates: 6.543ms
Generate rules: 256.616ms
Build stylesheet: 6.233ms
Potential classes:  10358
Active contexts:  2


(node:1386496) Warning: No such label 'JIT TOTAL' for console.timeEnd()


Source path: /home/path/to/OpenHands/frontend/src/tailwind.css
Finding changed files: 4.262ms
Reading changed files: 0.005ms
Sorting candidates: 0.004ms
Generate rules: 0.033ms
Build stylesheet: 0.002ms
Potential classes:  1
Active contexts:  2
JIT TOTAL: 18.001ms




Source path: /home/path/to/OpenHands/frontend/src/index.css
JIT TOTAL: 0.41ms




Source path: /home/path/to/OpenHands/frontend/node_modules/@xterm/xterm/css/xterm.css
JIT TOTAL: 1.074ms


INFO:     127.0.0.1:42780 - "GET /api/options/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:42790 - "GET /api/options/security-analyzers HTTP/1.1" 200 OK
INFO:     127.0.0.1:42794 - "GET /api/options/agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:42810 - "GET /api/options/security-analyzers HTTP/1.1" 200 OK
INFO:     127.0.0.1:42812 - "GET /api/options/agents HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 42822) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJjNDk4OGFmNy01ODlmLTRlODctODhjMS1lN2ZlZTBhODk0N2YifQ.Rp1GN68dbXvDUW2Jvr_UX3SCSiLAwlTrHprPmuiVuss" [accepted]
[92m19:37:59 - openhands:ERROR[0m: auth.py:27 - Invalid token
INFO:     connection open
INFO:     connection closed
INFO:     127.0.0.1:42838 - "GET /api/options/models HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 49862) - "WebSocket /ws" [accepted]
[92m19:38:07 - openhands:INFO[0m: listen.py:328 - New session: 320351f6-5766-40f4-a0fc-8508fb043be0
INFO:     connection open
[92m19:38:07 - openhands:DEBUG[0m: llm.py:125 - Model info: {'key': 'claude-3-5-sonnet-20240620', 'max_tokens': 8192, 'max_input_tokens': 200000, 'max_output_tokens': 8192, 'input_cost_per_token': 3e-06, 'cache_creation_input_token_cost': 3.75e-06, 'cache_read_input_token_cost': 3e-07, 'input_cost_per_character': None, 'input_cost_per_token_above_128k_tokens': None, 'input_cost_per_query': None, 'input_cost_per_second': None, 'input_cost_per_audio_token': None, 'output_cost_per_token': 1.5e-05, 'output_cost_per_audio_token': None, 'output_cost_per_character': None, 'output_cost_per_token_above_128k_tokens': None, 'output_cost_per_character_above_128k_tokens': None, 'output_cost_per_second': None, 'output_vector_size': None, 'litellm_provider': 'anthropic', 'mode': 'chat', 'supported_openai_params': ['stream', 'stop', 'temperature', 'top_p', 'max_tokens', 'max_completion_tokens', 'tools', 'tool_choice', 'extra_headers'], 'supports_system_messages': None, 'supports_response_schema': None, 'supports_vision': True, 'supports_function_calling': True, 'supports_assistant_prefill': True, 'supports_prompt_caching': True, 'supports_audio_input': False, 'supports_audio_output': False}
[92m19:38:07 - openhands:DEBUG[0m: llm.py:181 - LLM: model has vision enabled
[92m19:38:07 - openhands:DEBUG[0m: llm.py:183 - LLM: caching prompt enabled
[92m19:38:07 - openhands:DEBUG[0m: llm.py:185 - LLM: model supports function calling
[92m19:38:07 - openhands:INFO[0m: codeact_agent.py:113 - TOOLS loaded for CodeActAgent: [
  {
    "type": "function",
    "function": {
      "name": "execute_bash",
      "description": "Execute a bash command in the terminal.\n* Long running commands: For commands that may run indefinitely, it should be run in the background and the output should be redirected to a file, e.g. command = `python3 app.py > server.log 2>&1 &`.\n* Interactive: If a bash command returns exit code `-1`, this means the process is not yet finished. The assistant must then send a second call to terminal with an empty `command` (which will retrieve any additional logs), or it can send additional text (set `command` to the text) to STDIN of the running process, or it can send command=`ctrl+c` to interrupt the process.\n* Timeout: If a command execution result says \"Command timed out. Sending SIGINT to the process\", the assistant should retry running the command in the background.\n",
      "parameters": {
        "type": "object",
        "properties": {
          "command": {
            "type": "string",
            "description": "The bash command to execute. Can be empty to view additional logs when previous exit code is `-1`. Can be `ctrl+c` to interrupt the currently running process."
          }
        },
        "required": [
          "command"
        ]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "finish",
      "description": "Finish the interaction when the task is complete OR if the assistant cannot proceed further with the task."
    }
  },
  {
    "type": "function",
    "function": {
      "name": "str_replace_editor",
      "description": "Custom editing tool for viewing, creating and editing files\n* State is persistent across command calls and discussions with the user\n* If `path` is a file, `view` displays the result of applying `cat -n`. If `path` is a directory, `view` lists non-hidden files and directories up to 2 levels deep\n* The `create` command cannot be used if the specified `path` already exists as a file\n* If a `command` generates a long output, it will be truncated and marked with `<response clipped>`\n* The `undo_edit` command will revert the last edit made to the file at `path`\n\nNotes for using the `str_replace` command:\n* The `old_str` parameter should match EXACTLY one or more consecutive lines from the original file. Be mindful of whitespaces!\n* If the `old_str` parameter is not unique in the file, the replacement will not be performed. Make sure to include enough context in `old_str` to make it unique\n* The `new_str` parameter should contain the edited lines that should replace the `old_str`\n",
      "parameters": {
        "type": "object",
        "properties": {
          "command": {
            "description": "The commands to run. Allowed options are: `view`, `create`, `str_replace`, `insert`, `undo_edit`.",
            "enum": [
              "view",
              "create",
              "str_replace",
              "insert",
              "undo_edit"
            ],
            "type": "string"
          },
          "path": {
            "description": "Absolute path to file or directory, e.g. `/repo/file.py` or `/repo`.",
            "type": "string"
          },
          "file_text": {
            "description": "Required parameter of `create` command, with the content of the file to be created.",
            "type": "string"
          },
          "old_str": {
            "description": "Required parameter of `str_replace` command containing the string in `path` to replace.",
            "type": "string"
          },
          "new_str": {
            "description": "Optional parameter of `str_replace` command containing the new string (if not given, no string will be added). Required parameter of `insert` command containing the string to insert.",
            "type": "string"
          },
          "insert_line": {
            "description": "Required parameter of `insert` command. The `new_str` will be inserted AFTER the line `insert_line` of `path`.",
            "type": "integer"
          },
          "view_range": {
            "description": "Optional parameter of `view` command when `path` points to a file. If none is given, the full file is shown. If provided, the file will be shown in the indicated line number range, e.g. [11, 12] will show lines 11 and 12. Indexing at 1 to start. Setting `[start_line, -1]` shows all lines from `start_line` to the end of the file.",
            "items": {
              "type": "integer"
            },
            "type": "array"
          }
        },
        "required": [
          "command",
          "path"
        ]
      }
    }
  }
]
[92m19:38:07 - openhands:DEBUG[0m: stream.py:144 - Adding ChangeAgentStateAction id=0 from USER
[92m19:38:07 - openhands:DEBUG[0m: stream.py:144 - Adding AgentStateChangedObservation id=1 from AGENT
[92m19:38:07 - openhands:DEBUG[0m: agent_session.py:177 - Initializing runtime `eventstream` now...
[92m19:38:07 - openhands:DEBUG[0m: edit.py:114 - It is not recommended to cache draft editor LLM prompts as it may incur high costs for the same prompt. Automatically setting caching_prompt=false.
[92m19:38:07 - openhands:DEBUG[0m: llm.py:125 - Model info: {'key': 'claude-3-5-sonnet-20240620', 'max_tokens': 8192, 'max_input_tokens': 200000, 'max_output_tokens': 8192, 'input_cost_per_token': 3e-06, 'cache_creation_input_token_cost': 3.75e-06, 'cache_read_input_token_cost': 3e-07, 'input_cost_per_character': None, 'input_cost_per_token_above_128k_tokens': None, 'input_cost_per_query': None, 'input_cost_per_second': None, 'input_cost_per_audio_token': None, 'output_cost_per_token': 1.5e-05, 'output_cost_per_audio_token': None, 'output_cost_per_character': None, 'output_cost_per_token_above_128k_tokens': None, 'output_cost_per_character_above_128k_tokens': None, 'output_cost_per_second': None, 'output_vector_size': None, 'litellm_provider': 'anthropic', 'mode': 'chat', 'supported_openai_params': ['stream', 'stop', 'temperature', 'top_p', 'max_tokens', 'max_completion_tokens', 'tools', 'tool_choice', 'extra_headers'], 'supports_system_messages': None, 'supports_response_schema': None, 'supports_vision': True, 'supports_function_calling': True, 'supports_assistant_prefill': True, 'supports_prompt_caching': True, 'supports_audio_input': False, 'supports_audio_output': False}
[92m19:38:07 - openhands:DEBUG[0m: llm.py:181 - LLM: model has vision enabled
[92m19:38:07 - openhands:DEBUG[0m: llm.py:185 - LLM: model supports function calling
[92m19:38:07 - openhands:DEBUG[0m: edit.py:121 - [Draft edit functionality] enabled with LLM: LLM(model=claude-3-5-sonnet-20240620)
[92m19:38:07 - openhands:INFO[0m: runtime_build.py:176 - Building image: ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc_4o5gt9id7p46i5re
[92m19:38:07 - openhands:DEBUG[0m: docker.py:184 - Checking, if image exists locally:
ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc_4o5gt9id7p46i5re
[92m19:38:07 - openhands:DEBUG[0m: docker.py:190 - Image ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc_4o5gt9id7p46i5re not found locally
[92m19:38:07 - openhands:DEBUG[0m: docker.py:184 - Checking, if image exists locally:
ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc
[92m19:38:07 - openhands:DEBUG[0m: docker.py:193 - Image not found locally. Trying to pull it, please wait...
[92m19:38:08 - openhands:DEBUG[0m: docker.py:223 - Image could not be pulled: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=oh_v0.11.0_lixeiy5qfzxkjbnc&fromImage=ghcr.io%2Fall-hands-ai%2Fruntime: Internal Server Error ("manifest unknown")
[92m19:38:08 - openhands:DEBUG[0m: docker.py:184 - Checking, if image exists locally:
ghcr.io/all-hands-ai/runtime:oh_v0.11.0_nikolaik_s_python-nodejs_t_python3.12-nodejs22
[92m19:38:08 - openhands:DEBUG[0m: docker.py:193 - Image not found locally. Trying to pull it, please wait...
[92m19:38:10 - openhands:DEBUG[0m: docker.py:223 - Image could not be pulled: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=oh_v0.11.0_nikolaik_s_python-nodejs_t_python3.12-nodejs22&fromImage=ghcr.io%2Fall-hands-ai%2Fruntime: Internal Server Error ("manifest unknown")
[92m19:38:10 - openhands:DEBUG[0m: runtime_build.py:219 - Build [ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc_4o5gt9id7p46i5re] from scratch
[92m19:38:10 - openhands:DEBUG[0m: runtime_build.py:250 - Building source distribution using project root: /home/path/to/OpenHands
[92m19:38:10 - openhands:DEBUG[0m: docker.py:184 - Checking, if image exists locally:
ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc_4o5gt9id7p46i5re
[92m19:38:10 - openhands:DEBUG[0m: docker.py:190 - Image ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc_4o5gt9id7p46i5re not found locally
[92m19:38:10 - openhands:DEBUG[0m: docker.py:184 - Checking, if image exists locally:
ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc
[92m19:38:10 - openhands:DEBUG[0m: docker.py:190 - Image ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc not found locally
[92m19:38:10 - openhands:DEBUG[0m: docker.py:184 - Checking, if image exists locally:
ghcr.io/all-hands-ai/runtime:oh_v0.11.0_nikolaik_s_python-nodejs_t_python3.12-nodejs22
[92m19:38:10 - openhands:DEBUG[0m: docker.py:190 - Image ghcr.io/all-hands-ai/runtime:oh_v0.11.0_nikolaik_s_python-nodejs_t_python3.12-nodejs22 not found locally
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - unknown flag: --progress
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - See 'docker --help'.
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - Usage:  docker [OPTIONS] COMMAND
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - A self-sufficient runtime for containers
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - Common Commands:
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - run         Create and run a new container from an image
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - exec        Execute a command in a running container
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - ps          List containers
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - build       Build an image from a Dockerfile
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - pull        Download an image from a registry
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - push        Upload an image to a registry
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - images      List images
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - login       Log in to a registry
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - logout      Log out from a registry
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - search      Search Docker Hub for images
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - version     Show the Docker version information
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - info        Display system-wide information
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - Management Commands:
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - builder     Manage builds
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - container   Manage containers
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - context     Manage contexts
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - image       Manage images
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - manifest    Manage Docker image manifests and manifest lists
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - network     Manage networks
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - plugin      Manage plugins
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - system      Manage Docker
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - trust       Manage trust on Docker images
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - volume      Manage volumes
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - Swarm Commands:
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - swarm       Manage Swarm
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - Commands:
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - attach      Attach local standard input, output, and error streams to a running container
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - commit      Create a new image from a container's changes
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - cp          Copy files/folders between a container and the local filesystem
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - create      Create a new container
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - diff        Inspect changes to files or directories on a container's filesystem
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - events      Get real time events from the server
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - export      Export a container's filesystem as a tar archive
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - history     Show the history of an image
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - import      Import the contents from a tarball to create a filesystem image
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - inspect     Return low-level information on Docker objects
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - kill        Kill one or more running containers
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - load        Load an image from a tar archive or STDIN
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - logs        Fetch the logs of a container
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - pause       Pause all processes within one or more containers
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - port        List port mappings or a specific mapping for the container
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - rename      Rename a container
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - restart     Restart one or more containers
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - rm          Remove one or more containers
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - rmi         Remove one or more images
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - save        Save one or more images to a tar archive (streamed to STDOUT by default)
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - start       Start one or more stopped containers
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - stats       Display a live stream of container(s) resource usage statistics
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - stop        Stop one or more running containers
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - top         Display the running processes of a container
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - unpause     Unpause all processes within one or more containers
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - update      Update configuration of one or more containers
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - wait        Block until one or more containers stop, then print their exit codes
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - Global Options:
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - --config string      Location of client config files (default
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - "/home/domi/.docker")
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - -c, --context string     Name of the context to use to connect to the
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - daemon (overrides DOCKER_HOST env var and
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - default context set with "docker context use")
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - -D, --debug              Enable debug mode
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - -H, --host list          Daemon socket to connect to
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - -l, --log-level string   Set the logging level ("debug", "info",
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - "warn", "error", "fatal") (default "info")
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - --tls                Use TLS; implied by --tlsverify
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - --tlscacert string   Trust certs signed only by this CA (default
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - "/home/domi/.docker/ca.pem")
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - --tlscert string     Path to TLS certificate file (default
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - "/home/domi/.docker/cert.pem")
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - --tlskey string      Path to TLS key file (default
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - "/home/domi/.docker/key.pem")
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - --tlsverify          Use TLS and verify the remote
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - -v, --version            Print version information and quit
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - Run 'docker COMMAND --help' for more information on a command.
[92m19:38:10 - openhands:DEBUG[0m: docker.py:228 - For more help on how to use Docker, head to https://docs.docker.com/go/guides/
[92m19:38:10 - openhands:ERROR[0m: docker.py:122 - Image build failed:
Command '['docker', 'buildx', 'build', '--progress=plain', '--build-arg=OPENHANDS_RUNTIME_VERSION=0.11.0', '--build-arg=OPENHANDS_RUNTIME_BUILD_TIME=2024-10-29T19:38:10.214254', '--tag=ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc_4o5gt9id7p46i5re', '--load', '/tmp/tmpoyr5_smp']' returned non-zero exit status 125.
[92m19:38:10 - openhands:ERROR[0m: docker.py:123 - Command output:

[92m19:38:10 - openhands:ERROR[0m: agent_session.py:190 - Runtime initialization failed: Command '['docker', 'buildx', 'build', '--progress=plain', '--build-arg=OPENHANDS_RUNTIME_VERSION=0.11.0', '--build-arg=OPENHANDS_RUNTIME_BUILD_TIME=2024-10-29T19:38:10.214254', '--tag=ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc_4o5gt9id7p46i5re', '--load', '/tmp/tmpoyr5_smp']' returned non-zero exit status 125.
Traceback (most recent call last):
  File "/home/path/to/OpenHands/openhands/server/session/agent_session.py", line 188, in _create_runtime
    await self.runtime.connect()
  File "/home/path/to/OpenHands/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 197, in connect
    self.runtime_container_image = build_runtime_image(
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/path/to/OpenHands/openhands/runtime/utils/runtime_build.py", line 134, in build_runtime_image
    result = build_runtime_image_in_folder(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/path/to/OpenHands/openhands/runtime/utils/runtime_build.py", line 223, in build_runtime_image_in_folder
    _build_sandbox_image(
  File "/home/path/to/OpenHands/openhands/runtime/utils/runtime_build.py", line 350, in _build_sandbox_image
    image_name = runtime_builder.build(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/path/to/OpenHands/openhands/runtime/builder/docker.py", line 114, in build
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['docker', 'buildx', 'build', '--progress=plain', '--build-arg=OPENHANDS_RUNTIME_VERSION=0.11.0', '--build-arg=OPENHANDS_RUNTIME_BUILD_TIME=2024-10-29T19:38:10.214254', '--tag=ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc_4o5gt9id7p46i5re', '--load', '/tmp/tmpoyr5_smp']' returned non-zero exit status 125.
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=CalledProcessError(125, ['docker', 'buildx', 'build', '--progress=plain', '--build-arg=OPENHANDS_RUNTIME_VERSION=0.11.0', '--build-arg=OPENHANDS_RUNTIME_BUILD_TIME=2024-10-29T19:38:10.214254', '--tag=ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc_4o5gt9id7p46i5re', '--load', '/tmp/tmpoyr5_smp'])>
Traceback (most recent call last):
  File "/home/domi/.pyenv/versions/3.12.7/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/path/to/OpenHands/openhands/server/session/agent_session.py", line 88, in _start_thread
    asyncio.run(self._start(*args), debug=True)
  File "/home/domi/.pyenv/versions/3.12.7/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/domi/.pyenv/versions/3.12.7/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/path/to/OpenHands/openhands/server/session/agent_session.py", line 106, in _start
    await self._create_runtime(
  File "/home/path/to/OpenHands/openhands/server/session/agent_session.py", line 188, in _create_runtime
    await self.runtime.connect()
  File "/home/path/to/OpenHands/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 197, in connect
    self.runtime_container_image = build_runtime_image(
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/path/to/OpenHands/openhands/runtime/utils/runtime_build.py", line 134, in build_runtime_image
    result = build_runtime_image_in_folder(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/path/to/OpenHands/openhands/runtime/utils/runtime_build.py", line 223, in build_runtime_image_in_folder
    _build_sandbox_image(
  File "/home/path/to/OpenHands/openhands/runtime/utils/runtime_build.py", line 350, in _build_sandbox_image
    image_name = runtime_builder.build(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/path/to/OpenHands/openhands/runtime/builder/docker.py", line 114, in build
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['docker', 'buildx', 'build', '--progress=plain', '--build-arg=OPENHANDS_RUNTIME_VERSION=0.11.0', '--build-arg=OPENHANDS_RUNTIME_BUILD_TIME=2024-10-29T19:38:10.214254', '--tag=ghcr.io/all-hands-ai/runtime:oh_v0.11.0_lixeiy5qfzxkjbnc_4o5gt9id7p46i5re', '--load', '/tmp/tmpoyr5_smp']' returned non-zero exit status 125.
```
```

**Comment by enyst** [comment]
I see a line where docker reports an unknown parameter - could you please make sure to update docker for your platform?

**Comment by Domiii** [comment]
> I see a line where docker reports an unknown parameter - could you please make sure to update docker for your platform?

* I just followed instructions to uninstall all previous versions and am now using the official docker installation for Ubuntu (I'm on 22.04) [here](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository).
* Then jumped through several more hoops to (i) get it registered and started as a demon and (ii) also not require `sudo`.

It works now 🥳

**Comment by Domiii** [comment]
> I see a line where docker reports an unknown parameter - could you please make sure to update docker for your platform?

For reference, I think, you are referring to this line hidden in my very long pasted log -

```
unknown flag: --progress
```

Would be cool to surface these things more directly, but I understand if you don't have time to add more descriptive nesting of exceptions right now.

Again, thanks for the help!

**Comment by enyst** [comment]
You're so right! 😅 I went through the whole log, and after I was done, I realized I haven't copied it, so... I described it, rather than going through it one more time 😊. Sorry about that.

We were making some improvements to logs just these days, and more will be coming.

Glad you got it solved!
