### ISSUE TITLE
[Bug]: ValueError when fetching Docker version

### ISSUE THREAD

**Issue by Polygons1** [All-Hands-AI/OpenHands#4717]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Enter a message and it will happen.

### OpenHands Installation

Docker command in README

### OpenHands Version

0.12

### Operating System

Linux

### Logs, Errors, Screenshots, and Additional Context

ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=ValueError("invalid literal for int() with base 10: '24+dfsg1'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 88, in _start_thread
    asyncio.run(self._start(*args), debug=True)
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 106, in _start
    await self._create_runtime(
  File "/app/openhands/server/session/agent_session.py", line 179, in _create_runtime
    self.runtime = runtime_cls(
                   ^^^^^^^^^^^^
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 163, in __init__
    self.runtime_builder = DockerRuntimeBuilder(self.docker_client)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/builder/docker.py", line 20, in __init__
    if false:
       ^^^^^^^
ValueError: invalid literal for int() with base 10: '24+dfsg1'

my Docker version is 20.10.24+dfsg1, build 297e128

**Comment by Polygons1** [comment]
it works, thanks!
