### ISSUE TITLE
[Bug]: Invalid 'tools[2].function.description': string too long. Expected a string with maximum length 1024, but got a string with length 4394 instead.

### ISSUE THREAD

**Issue by twhite54** [All-Hands-AI/OpenHands#4838]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

1. I'm using Azure GPT-4o. 
2. Send any message. ie. "Write hello world in python"
3. Error message, "Agent is running task" is visible at the bottom of the page , dots appear in chat as if it was responding back. Nothing happens in the ui until you refresh the page - then the error message in the logs section labeled 'in UI' appears. 

### OpenHands Installation

Docker command in README

### OpenHands Version

openhands:0.12

### Operating System

WSL on Windows

### Logs, Errors, Screenshots, and Additional Context

- Receive this error in UI:

litellm.BadRequestError: AzureException BadRequestError - Error code: 400 - {'error': {'message': "Invalid 'tools[2].function.description': string too long. Expected a string with maximum length 1024, but got a string with length 4394 instead.", 'type': 'invalid_request_error', 'param': 'tools[2].function.description', 'code': 'string_above_max_length'}}

- Receive this error in Ubuntu WLS:

 agent_controller.py:135 - [Agent Controller 556a2487-b5f2-42a0-8594-1b934d0842cc] Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/AzureOpenAI/azure.py", line 516, in completion
    headers, response = self.make_sync_azure_openai_chat_completion_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/AzureOpenAI/azure.py", line 323, in make_sync_azure_openai_chat_completion_request
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/AzureOpenAI/azure.py", line 315, in make_sync_azure_openai_chat_completion_request
    raw_response = azure_client.chat.completions.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_legacy_response.py", line 356, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 815, in create
    return self._post(
           ^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1058, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid 'tools[2].function.description': string too long. Expected a string with maximum length 1024, but got a string with length 4394 instead.", 'type': 'invalid_request_error', 'param': 'tools[2].function.description', 'code': 'string_above_max_length'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1160, in completion
    response = azure_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/AzureOpenAI/azure.py", line 545, in completion
    raise AzureOpenAIError(
litellm.llms.AzureOpenAI.azure.AzureOpenAIError: Error code: 400 - {'error': {'message': "Invalid 'tools[2].function.description': string too long. Expected a string with maximum length 1024, but got a string with length 4394 instead.", 'type': 'invalid_request_error', 'param': 'tools[2].function.description', 'code': 'string_above_max_length'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/openhands/controller/agent_controller.py", line 168, in start_step_loop
    await self._step()
  File "/app/openhands/controller/agent_controller.py", line 464, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/agenthub/codeact_agent/codeact_agent.py", line 359, in step
    response = self.llm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/llm/llm.py", line 196, in wrapper
    resp: ModelResponse = completion_unwrapped(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1013, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 903, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2999, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 1870, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: litellm.BadRequestError: AzureException BadRequestError - Error code: 400 - {'error': {'message': "Invalid 'tools[2].function.description': string too long. Expected a string with maximum length 1024, but got a string with length 4394 instead.", 'type': 'invalid_request_error', 'param': 'tools[2].function.description', 'code': 'string_above_max_length'}}

02:52:18 - openhands:INFO: agent_controller.py:135 - [Agent Controller 556a2487-b5f2-42a0-8594-1b934d0842cc] Setting agent(CodeActAgent) state from AgentState.RUNNING to AgentState.ERROR

**Comment by malhotra5** [comment]
I believe this occurs due to the length of the tool description for `_BROWSER_DESCRIPTION` in `openhands/agenthub/codeact_agent/function_calling.py`. A workaround for now is to use Claude!

A possible fix for this could be to split the current description into multiple tools?

**Comment by mamoodi** [comment]
Going to close this as duplicate and the original is closed.
