### ISSUE TITLE
[Bug]: Getting error litellm.BadRequestError: OpenAIException 

### ISSUE THREAD

**Issue by 316682032** [All-Hands-AI/OpenHands#4880]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

test

"I'm ready to assist you! What would you like to do today?"

test2

litellm.BadRequestError: OpenAIException - Error code: 400 - bad request

![test](https://github.com/user-attachments/assets/3b5cfcf3-5e80-4c01-8162-8e5ab7ec40ce)
![test2](https://github.com/user-attachments/assets/ad5203ce-3a1b-4fc3-8671-0325ad76b026)

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by 316682032** [comment]
[Agent Controller 6526f290-2ebf-4a93-87ad-8985f305ff1e] LEVEL 0 LOCAL STEP 1 GLOBAL STEP 1
2024-11-11 01:11:50 
2024-11-11 01:11:50 
2024-11-11 01:11:50 Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
2024-11-11 01:11:50 LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
2024-11-11 01:11:50 
2024-11-11 01:11:50 Traceback (most recent call last):
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 854, in completion
2024-11-11 01:11:50     raise e
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 790, in completion
2024-11-11 01:11:50     self.make_sync_openai_chat_completion_request(
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 649, in make_sync_openai_chat_completion_request
2024-11-11 01:11:50     raise e
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 631, in make_sync_openai_chat_completion_request
2024-11-11 01:11:50     raw_response = openai_client.chat.completions.with_raw_response.create(
2024-11-11 01:11:50                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/openai/_legacy_response.py", line 356, in wrapped
2024-11-11 01:11:50     return cast(LegacyAPIResponse[R], func(*args, **kwargs))
2024-11-11 01:11:50                                       ^^^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 274, in wrapper
2024-11-11 01:11:50     return func(*args, **kwargs)
2024-11-11 01:11:50            ^^^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 815, in create
2024-11-11 01:11:50     return self._post(
2024-11-11 01:11:50            ^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1277, in post
2024-11-11 01:11:50     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
2024-11-11 01:11:50                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 954, in request
2024-11-11 01:11:50     return self._request(
2024-11-11 01:11:50            ^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1058, in _request
2024-11-11 01:11:50     raise self._make_status_error_from_response(err.response) from None
2024-11-11 01:11:50 openai.BadRequestError: Error code: 400 - bad request
2024-11-11 01:11:50 
2024-11-11 01:11:50 During handling of the above exception, another exception occurred:
2024-11-11 01:11:50 
2024-11-11 01:11:50 Traceback (most recent call last):
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1587, in completion
2024-11-11 01:11:50     raise e
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1560, in completion
2024-11-11 01:11:50     response = openai_chat_completions.completion(
2024-11-11 01:11:50                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 864, in completion
2024-11-11 01:11:50     raise OpenAIError(
2024-11-11 01:11:50 litellm.llms.OpenAI.openai.OpenAIError: Error code: 400 - bad request
2024-11-11 01:11:50 
2024-11-11 01:11:50 During handling of the above exception, another exception occurred:
2024-11-11 01:11:50 
2024-11-11 01:11:50 Traceback (most recent call last):
2024-11-11 01:11:50   File "/app/openhands/controller/agent_controller.py", line 195, in start_step_loop
2024-11-11 01:11:50     await self._step()
2024-11-11 01:11:50   File "/app/openhands/controller/agent_controller.py", line 468, in _step
2024-11-11 01:11:50     action = self.agent.step(self.state)
2024-11-11 01:11:50              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/openhands/agenthub/codeact_agent/codeact_agent.py", line 359, in step
2024-11-11 01:11:50     response = self.llm.completion(**params)
2024-11-11 01:11:50                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
2024-11-11 01:11:50     return copy(f, *args, **kw)
2024-11-11 01:11:50            ^^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
2024-11-11 01:11:50     do = self.iter(retry_state=retry_state)
2024-11-11 01:11:50          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
2024-11-11 01:11:50     result = action(retry_state)
2024-11-11 01:11:50              ^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
2024-11-11 01:11:50     self._add_action_func(lambda rs: rs.outcome.result())
2024-11-11 01:11:50                                      ^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
2024-11-11 01:11:50     return self.__get_result()
2024-11-11 01:11:50            ^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
2024-11-11 01:11:50     raise self._exception
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
2024-11-11 01:11:50     result = fn(*args, **kwargs)
2024-11-11 01:11:50              ^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/openhands/llm/llm.py", line 196, in wrapper
2024-11-11 01:11:50     resp: ModelResponse = completion_unwrapped(*args, **kwargs)
2024-11-11 01:11:50                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1013, in wrapper
2024-11-11 01:11:50     raise e
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 903, in wrapper
2024-11-11 01:11:50     result = original_function(*args, **kwargs)
2024-11-11 01:11:50              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2999, in completion
2024-11-11 01:11:50     raise exception_type(
2024-11-11 01:11:50           ^^^^^^^^^^^^^^^
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
2024-11-11 01:11:50     raise e
2024-11-11 01:11:50   File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 334, in exception_type
2024-11-11 01:11:50     raise BadRequestError(
2024-11-11 01:11:50 litellm.exceptions.BadRequestError: litellm.BadRequestError: OpenAIException - Error code: 400 - bad request

**Comment by enyst** [comment]
Thank you for the report. What model, provider, base url did you enter in the Settings window?
