### ISSUE TITLE
[Bug]: Openhands container shuts down immediately (UID not unique)

### ISSUE THREAD

**Issue by malhotra5** [All-Hands-AI/OpenHands#4891]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I ran `make start-backend`; openhands was unable to connect to the docker container and exceed max retries. Upon further inspection it seems the container immediately shut down shortly after it is created. I ran `docker logs d9af0976fdb54a78b216f16ec8602a5541eac1ca2f5c6345b54b2251a2ce3a65` for more info and found the following stack trace

```
INFO:     Started server process [8]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/openhands/poetry/openhands-ai-5O4_aCHf-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openhands/micromamba/envs/openhands/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/openhands/code/openhands/runtime/action_execution_server.py", line 347, in lifespan
    client = ActionExecutor(
             ^^^^^^^^^^^^^^^
  File "/openhands/code/openhands/runtime/action_execution_server.py", line 97, in __init__
    _updated_user_id = init_user_and_working_directory(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openhands/code/openhands/runtime/utils/runtime_init.py", line 100, in init_user_and_working_directory
    raise RuntimeError(
RuntimeError: Failed to create user `openhands` with UID 0. Output: [useradd: UID 0 is not unique
]

ERROR:    Application startup failed. Exiting.
```

```
08:52:31 - openhands:ERROR: agent_session.py:197 - Runtime initialization failed: HTTPConnectionPool(host='localhost', port=31482): Max retries exceeded with url: /alive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12a0e4bc0>: Failed to establish a new connection: [Errno 61] Connection refused'))
Traceback (most recent call last):
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12a0e4bc0>: Failed to establish a new connection: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=31482): Max retries exceeded with url: /alive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12a0e4bc0>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/server/session/agent_session.py", line 195, in _create_runtime
    await self.runtime.connect()
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 219, in connect
    await call_sync_from_async(self._wait_until_alive)
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/utils/async_utils.py", line 18, in call_sync_from_async
    result = await coro
             ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/utils/async_utils.py", line 17, in <lambda>
    coro = loop.run_in_executor(None, lambda: fn(*args, **kwargs))
                                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 404, in _wait_until_alive
    send_request(
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/runtime/utils/request.py", line 60, in send_request
    response = session.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=31482): Max retries exceeded with url: /alive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12a0e4bc0>: Failed to establish a new connection: [Errno 61] Connection refused'))
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=31482): Max retries exceeded with url: /alive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12a0e4bc0>: Failed to establish a new connection: [Errno 61] Connection refused'))"))>
Traceback (most recent call last):
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x12a0e4bc0>: Failed to establish a new connection: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=31482): Max retries exceeded with url: /alive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12a0e4bc0>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/server/session/agent_session.py", line 92, in _start_thread
    asyncio.run(self._start(*args), debug=True)
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/server/session/agent_session.py", line 108, in _start
    await self._create_runtime(
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/server/session/agent_session.py", line 195, in _create_runtime
    await self.runtime.connect()
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 219, in connect
    await call_sync_from_async(self._wait_until_alive)
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/utils/async_utils.py", line 18, in call_sync_from_async
    result = await coro
             ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/utils/async_utils.py", line 17, in <lambda>
    coro = loop.run_in_executor(None, lambda: fn(*args, **kwargs))
                                              ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 404, in _wait_until_alive
    send_request(
  File "/Users/rohitmalhotra/Documents/Projects/OpenHands/openhands/runtime/utils/request.py", line 60, in send_request
    response = session.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohitmalhotra/Library/Caches/pypoetry/virtualenvs/openhands-ai-nue4wPdC-py3.12/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=31482): Max retries exceeded with url: /alive (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12a0e4bc0>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

### OpenHands Installation

Development workflow

### OpenHands Version

main

### Operating System

MacOS

**Comment by malhotra5** [comment]
Setting in my environment didn't work for me. I added it to my toml and that worked! Thanks for the help, closing this issue.
