### ISSUE TITLE
[Bug]: BedrockException - {"message":"The text field in the ContentBlock object at messages.28.content.1 is blank

### ISSUE THREAD

**Issue by scosenza** [All-Hands-AI/OpenHands#5339]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I'm using the OpenHands CLI started via:
```
docker run -it \
    --pull=always \
    -e DEBUG=1 \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.14.3-nikolaik \
    -e SANDBOX_USER_ID=$(id -u) \
    -e SANDBOX_TIMEOUT=5000 \
    -e LLM_API_KEY=$(iap-auth) \
    -e LLM_BASE_URL=https://devaigateway.redacted \
    -e LLM_MODEL=litellm_proxy/bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0 \
    -e WORKSPACE_MOUNT_PATH=/Users/steve_cosenza/airlab/repos/treehouse \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /Users/steve_cosenza/.cache:/root/.cache \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app-$(date +%Y%m%d%H%M%S) \
    docker.all-hands.dev/all-hands-ai/openhands:0.14.3 \
    python -m openhands.core.cli "$@"
```

I gave a prompt, and the agent was successfully making edits, and then we see the following in the output. Note that I didn't type anything at the "How can I help?" prompt, and it prompted me several times in the output, but then continued doing work:

```
Would you like me to make any additional changes to how the recordMode parameter is used within the method?

How can I help? >> 🤖 I see you're pointing out the `Disabled` case of the `RecordMode` sealed interface. 
The code structure looks correct as it:
1. Uses pattern matching with `when` to handle both cases of the sealed interface
2. Calls appropriate handlers for each case:
   - `handleResponseInRecordMode` for `Enabled` case with recording flags
   - `handleResponseInReplayMode` for `Disabled` case to verify against existing recordings

Is there something specific about the `Disabled` case that you'd like me to modify or improve?

How can I help? >> How can I help? >> 
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 860, in completion
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 796, in completion
    self.make_sync_openai_chat_completion_request(
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 657, in make_sync_openai_chat_completion_request
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 639, in make_sync_openai_chat_completion_request
    raw_response = openai_client.chat.completions.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_legacy_response.py", line 356, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 829, in create
    return self._post(
           ^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1278, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 955, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1059, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.28.content.1 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1605, in completion
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1578, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 870, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.28.content.1 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/openhands/controller/agent_controller.py", line 208, in start_step_loop
    await self._step()
  File "/app/openhands/controller/agent_controller.py", line 488, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/agenthub/codeact_agent/codeact_agent.py", line 336, in step
    response = self.llm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/llm/llm.py", line 202, in wrapper
    resp: ModelResponse = self._completion_unwrapped(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 960, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 849, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 3059, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2136, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 334, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: litellm.BadRequestError: Litellm_proxyException - Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.28.content.1 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}
02:55:45 - openhands:ERROR: agent_controller.py:214 - [Agent Controller default] Error while running the agent: litellm.BadRequestError: Litellm_proxyException - Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.28.content.1 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}
02:55:45 - openhands:ERROR: loop.py:23 - litellm.BadRequestError: Litellm_proxyException - Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.28.content.1 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}
```

### OpenHands Installation

Docker command in README

### OpenHands Version

0.14.3

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context
See https://github.com/All-Hands-AI/OpenHands/issues/4912 which also involved a BedrockException when using Airbnb's litellm based proxy which is also used here.
_No response_

**Comment by scosenza** [comment]
I can now repro this using the CLI when I past a message that has an empty line e.g.

```
How can I help? >> Do this 

And then do this

🤖 I apologize, but I need more specific information about what task you'd like me to help you with. Could you please provide more details about what you want me to do? For example:

- Are you trying to create, edit, or view a file?
- Do you want to run some commands in the terminal?
- Do you need help with browser automation?
- Do you want to execute some Python code?

Please let me know what specific task you'd like assistance with, and I'll be happy to help!

How can I help? >> How can I help? >> 
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 860, in completion
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 796, in completion
    self.make_sync_openai_chat_completion_request(
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 657, in make_sync_openai_chat_completion_request
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 639, in make_sync_openai_chat_completion_request
    raw_response = openai_client.chat.completions.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_legacy_response.py", line 356, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 829, in create
    return self._post(
           ^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1278, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 955, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1059, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.2.content.1 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1605, in completion
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1578, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/OpenAI/openai.py", line 870, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.2.content.1 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/openhands/controller/agent_controller.py", line 208, in start_step_loop
    await self._step()
  File "/app/openhands/controller/agent_controller.py", line 488, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/agenthub/codeact_agent/codeact_agent.py", line 336, in step
    response = self.llm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/llm/llm.py", line 202, in wrapper
    resp: ModelResponse = self._completion_unwrapped(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 960, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 849, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 3059, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2136, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 334, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: litellm.BadRequestError: Litellm_proxyException - Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.2.content.1 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}
18:40:58 - openhands:ERROR: agent_controller.py:214 - [Agent Controller default] Error while running the agent: litellm.BadRequestError: Litellm_proxyException - Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.2.content.1 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}
18:40:58 - openhands:ERROR: loop.py:23 - litellm.BadRequestError: Litellm_proxyException - Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.2.content.1 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}
```

**Comment by enyst** [comment]
Thanks for the repro steps!  Bedrock fails when content is empty, but this is weird because we have code handling that, and more importantly, your example isn't actually empty! Oops. Looking into it.

**Comment by scosenza** [comment]
Thanks for investigating this! It seems like OpenHands is processing each
line individually, as it responds to the first line before failing…
