### ISSUE TITLE
[Bug]: BedrockException - {"message":"The text field in the ContentBlock object at messages.3.content.0 is blank

### ISSUE THREAD

**Issue by scosenza** [All-Hands-AI/OpenHands#5722]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

```
0.16.1: Pulling from all-hands-ai/openhands
Digest: sha256:71e4d87b409c3cb3faf303d3c6eb8e04e0b8f7248f883f9a371980557a6ad30b
Status: Image is up to date for docker.all-hands.dev/all-hands-ai/openhands:0.16.1
Starting OpenHands...
Setting up enduser with id 501
Docker socket group id: 0
root:x:0:
Group with id 0 already exists
Running as enduser
How can I help? >> Read `tooling/backends/openhands/prompts/general.md` and `tooling/backends/openhands/prompts/bazel.md` for general instuctions. Your task is to improve the `projects/quicktest` README.md file.
🤖 I'll help you improve the README.md file for the quicktest project. Let me first read the instruction files and then check the current README.md content.

🤖 


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/openai/openai.py", line 609, in completion
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/openai/openai.py", line 545, in completion
    self.make_sync_openai_chat_completion_request(
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/openai/openai.py", line 411, in make_sync_openai_chat_completion_request
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/openai/openai.py", line 393, in make_sync_openai_chat_completion_request
    raw_response = openai_client.chat.completions.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_legacy_response.py", line 356, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 829, in create
    return self._post(
           ^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1280, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 957, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1061, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.3.content.0 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1595, in completion
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1568, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/openai/openai.py", line 619, in completion
    raise OpenAIError(
litellm.llms.openai.common_utils.OpenAIError: Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.3.content.0 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/openhands/controller/agent_controller.py", line 210, in start_step_loop
    await self._step()
  File "/app/openhands/controller/agent_controller.py", line 511, in _step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/agenthub/codeact_agent/codeact_agent.py", line 366, in step
    response = self.llm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/llm/llm.py", line 218, in wrapper
    resp: ModelResponse = self._completion_unwrapped(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 999, in wrapper
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 880, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2951, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2148, in exception_type
    raise e
  File "/app/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 338, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: litellm.BadRequestError: Litellm_proxyException - Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.3.content.0 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}
22:26:00 - openhands:ERROR: agent_controller.py:216 - [Agent Controller default] Error while running the agent: litellm.BadRequestError: Litellm_proxyException - Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.3.content.0 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}
22:26:00 - openhands:ERROR: loop.py:23 - litellm.BadRequestError: Litellm_proxyException - Error code: 400 - {'error': {'message': 'litellm.BadRequestError: BedrockException - {"message":"The text field in the ContentBlock object at messages.3.content.0 is blank. Add text to the text field, and try again."}\nReceived Model Group=bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '400'}}
steve_cosenza@Steves-MacBook-Pro quicktest % 
```

### OpenHands Installation

Docker command in README

### OpenHands Version

0.16.1

### Operating System

MacOS

**Comment by enyst** [comment]
Sorry, Steve, so what happened here is:
- we had a quick fix for bedrock on this issue https://github.com/All-Hands-AI/OpenHands/pull/4935
- it caused regressions https://github.com/All-Hands-AI/OpenHands/issues/5492
- we submitted an attempt to fix it on litellm instead https://github.com/BerriAI/litellm/pull/7177
- and we reverted it https://github.com/All-Hands-AI/OpenHands/pull/5539

Unfortunately, the litellm fix worked for bedrock, but not for bedrock via litellm_proxy. That was fixed a few days ago:
- https://github.com/BerriAI/litellm/issues/7169

The litellm version for the proxy is now updated in our `main`, but it wasn't at the time of our 0.16.1. release.

**Comment by scosenza** [comment]
Thanks for the detailed explanation! I'll pick this back up in January, and I'll make sure to upgrade when I do.
