### ISSUE TITLE
[Bug]: Error: Not a directory

### ISSUE THREAD

**Issue by avi12** [All-Hands-AI/OpenHands#5870]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

![image](https://github.com/user-attachments/assets/5d9488dd-b2c3-45a4-9168-3df6ddc0a256)

### OpenHands Installation

Docker command in README

### OpenHands Version

`main`

### Operating System

Windows

### Logs, Errors, Screenshots, and Additional Context

Plus the agent puts a ✅ next to the error Python result (#5637)
![image](https://github.com/user-attachments/assets/428d6d48-ee58-407b-8bbf-6d6a1d9481de)

The LLM is GPT-4o

**Comment by enyst** [comment]
Thank you for the report. Is the first screenshot how they appeared in Jupyter?

Do you have a log or trajectory (link to feedback) if possible?

**Comment by avi12** [comment]
> Thank you for the report. Is the first screenshot how they appeared in Jupyter?

Yes



> Do you have a log or trajectory (link to feedback) if possible?

Unfortunately, I don't have one; yesterday I started experimenting with building OH from source, which came with a whole can of gotchas moving between WSL and Windows

**Comment by avi12** [comment]
@enyst I [reproduced](https://www.all-hands.dev/share?share_id=8019b319061015369154c139c9e3587ee18e5f74ec4128d8d36dc5e9ef6f19c3) it when I built from source via WSL

**Comment by enyst** [comment]
In your screenshot there's only 1 ipython action that results in that error. Were there many of them in that chat box (not jupyter)?

Please try to run with DEBUG=1, so it saves details in the logs directory.

**Comment by avi12** [comment]
I always run with `DEBUG=1`/`debug=true` when building from source

**Comment by MohamedMohana** [comment]
Same issue here, did you find a solution ?

**Comment by enyst** [comment]
Can you paste the logs with the errors @MohamedMohana ?

**Comment by MohamedMohana** [comment]
I am running OpenHands on a Mac OS M1 system, version 15.2. Below is the process I followed for installation and execution:

## Steps Followed

1. Pulled the Docker image for OpenHands:
   ```bash
   docker pull docker.all-hands.dev/all-hands-ai/openhands:0.18
   ```

2. Set the workspace environment variable:
   ```bash
   export WORKSPACE_BASE=/Users/mohana/Documents/OpenHand
   ```

3. Verified the OpenHands state directory:
   ```bash
   ls -ld ~/.openhands-state
   ```

4. Updated permissions for the state directory:
   ```bash
   chmod u+rwx ~/.openhands-state
   ```

5. Ran the Docker container:
   ```bash
   docker run -it --rm --pull=always \
       -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.18-nikolaik \
       -e SANDBOX_USER_ID=$(id -u) \
       -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
       -v $WORKSPACE_BASE:/opt/workspace_base \
       -v /var/run/docker.sock:/var/run/docker.sock \
       -p 3000:3000 \
       --add-host host.docker.internal:host-gateway \
       --name openhands-app \
       docker.all-hands.dev/all-hands-ai/openhands:0.18
   ```

## Issue Observed

when the chat asked to download the folders:
```
15:21:56 - openhands:WARNING: files.py:90 - 500 Server Error: Internal Server Error for url: http://host.docker.internal:32183/execute_action
Details: Traceback (most recent call last):
  File "/openhands/code/openhands/runtime/action_execution_server.py", line 511, in execute_action
    observation = await client.run_action(action)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openhands/code/openhands/runtime/action_execution_server.py", line 173, in run_action
    observation = await getattr(self, action_type)(action)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openhands/code/openhands/runtime/action_execution_server.py", line 295, in read
    working_dir = self.bash_session.workdir
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openhands/code/openhands/runtime/utils/bash.py", line 92, in workdir
    return self._get_working_directory()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openhands/code/openhands/runtime/utils/bash.py", line 98, in _get_working_directory
    raise RuntimeError(
RuntimeError: Failed to get working directory (exit code: 2): pwd
/workspace/Certs
```
