### ISSUE TITLE
how to fix this bug 

### ISSUE THREAD

**Issue by chenrongjian** [All-Hands-AI/OpenHands#5898]
12:19:09 - openhands:INFO: codeact_agent.py:90 - Function calling not enabled for model Qwen/Qwen2.5-72B-Instruct. Mocking function calling via prompting.
12:19:09 - openhands:INFO: manager.py:325 - _get_event_stream:35566bfc84354dfa9c1bc187c1d4d555
12:19:09 - openhands:INFO: manager.py:328 - found_local_agent_loop:35566bfc84354dfa9c1bc187c1d4d555
INFO:     172.17.0.1:55584 - "POST /api/conversations HTTP/1.1" 200 OK
12:19:09 - openhands:ERROR: analyzer.py:62 - Error creating Invariant Security Analyzer container. Please check that Docker is running or disable the Security Analyzer in settings.
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=DockerException("Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))")>
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/app/.venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/app/.venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 223, in _retrieve_server_version    
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 246, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')) 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 103, in _start_thread
    asyncio.run(self._start(*args), debug=True)
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 124, in _start
    self._create_security_analyzer(config.security.security_analyzer)
  File "/app/openhands/server/session/agent_session.py", line 190, in _create_security_analyzer
    self.security_analyzer = options.SecurityAnalyzers.get(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/security/invariant/analyzer.py", line 66, in __init__
    raise ex
  File "/app/openhands/security/invariant/analyzer.py", line 60, in __init__
    self.docker_client = docker.from_env()
                         ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/client.py", line 94, in from_env
    return cls(
           ^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 207, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 230, in _retrieve_server_version    
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
INFO:     ('172.17.0.1', 55586) - "WebSocket /socket.io/?latest_event_id=-1&conversation_id=35566bfc84354dfa9c1bc187c1d4d555&EIO=4&transport=websocket" [accepted]
INFO:     172.17.0.1:55584 - "GET /api/options/config HTTP/1.1" 200 OK
12:19:09 - openhands:INFO: listen_socket.py:27 - sio:connect: xjlopQ-BoiD9j1pSAAAF
12:19:09 - openhands:INFO: manager.py:182 - join_conversation:35566bfc84354dfa9c1bc187c1d4d555:xjlopQ-BoiD9j1pSAAAF
12:19:09 - openhands:INFO: manager.py:325 - _get_event_stream:35566bfc84354dfa9c1bc187c1d4d555
12:19:09 - openhands:INFO: manager.py:328 - found_local_agent_loop:35566bfc84354dfa9c1bc187c1d4d555
12:19:19 - openhands:INFO: manager.py:395 - _cleanup_session:0299593f83e04e878ff95a7d3592c08b
12:19:19 - openhands:INFO: manager.py:419 - _close_session:0299593f83e04e878ff95a7d3592c08b
12:19:19 - openhands:INFO: manager.py:427 - removing connections: []
12:19:19 - openhands:INFO: manager.py:436 - closing_session:0299593f83e04e878ff95a7d3592c08b
INFO:     172.17.0.1:40240 - "GET /api/options/config HTTP/1.1" 200 OK

**Comment by mamoodi** [comment]
There's multiple errors going on here. Can you clarify what you are doing.
* How you are running OpenHands?
* What you are using in the Settings?
* What OS you are running?

**Comment by chenrongjian** [comment]
How you are running OpenHands?
reponse:I used this order in the vscode teminal git bash:
docker run -it --rm --pull=always \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.17-nikolaik \
    -e LOG_ALL_EVENTS=true \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v ~/.openhands-state:/.openhands-state \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.17
What you are using in the Settings?
response:I used the  model Qwen/Qwen2.5-72B-Instruct and xai 
What OS you are running?
window11

**Comment by mamoodi** [comment]
For Windows, you must run in the WSL terminal. See https://docs.all-hands.dev/modules/usage/installation#system-requirements
